### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/78645/en.xml

### ISSUE THREAD

**Issue by dammed5** [pymedusa/SickRage#1030]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-4-amd64-x86_64-with-debian-8.5**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@ba2d9497c761ed1d0f375c9145c2782ec2f3a06c
Link to Log: https://gist.github.com/c5e5f5aae997ee1f18e9c18cdfc75e9a
### ERROR
```
SHOWQUEUE-ADD :: [ba2d949] 78645 Error while loading information from indexer theTVDB. Error: u'error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/78645/en.xml'
Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/show_queue.py", line 346, in run
    s = t[self.indexer_id]
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 953, in __getitem__
    self._getShowData(key, self.config['language'], True)
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 848, in _getShowData
    self.config['url_seriesInfo'] % (sid, getShowInLanguage)
  File "/opt/sickrage/lib/tvdb_api/tvdb_api.py", line 636, in _getetsrc
    raise tvdb_error(e)
tvdb_error: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/78645/en.xml
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@dammed5 looks like you internet was down or having issues in that moment. Did you try again ? did it worked?

**Comment by fernandog** [comment]
@p0psicles another case of error `None` - looks like no http status code, to internet was unreachable. Need to handle that in new tvdb

**Comment by Thraxis** [comment]
TheTVDB was down last night for some time
