### ISSUE TITLE
FINDSUBTITLES :: [3824246] Failed to refine video Traceback (most recent call last)

### ISSUE THREAD

**Issue by medariox** [pymedusa/SickRage#1034]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop/3824246
OS: Linux
What you did: nothing
What happened: ~~rato appeared~~ warning
What you expected: no warning
Logs:
```
2016-09-05 17:55:06 WARNING  FINDSUBTITLES :: [3824246] Failed to refine video
Traceback (most recent call last):
  File "/home/**********/.sickrage/lib/subliminal/core.py", line 543, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/**********/.sickrage/sickbeard/refiners/tvepisode.py", line 62, in refine
    enrich({'resolution': guess['screen_size'], 'format': guess['format']}, video, overwrite=False)
KeyError: u'screen_size'
```

**Comment by fernandog** [comment]
@medariox filename/release name?

**Comment by medariox** [comment]
Nothing special, should be this one:
```Keep.Down.with.the.Kabas.S12E13.HDTV.x264-CRIMSON.mkv```
