### ISSUE TITLE
Post-Prossesing Section not allowing me to save settings

### ISSUE THREAD

**Issue by JonathanGorbutt** [pymedusa/SickRage#1038]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Windows Server 2008 R2
What you did: Changed some settings / enabled post-prossessing
What happened: Went to save and it wouldn't save the settings
What you expected: For it to save the settings

I have tried re-installing this twice now and nothing.

**Comment by fernandog** [comment]
@JonathanGorbutt already fixed in develop. Sorry about that.

**Comment by JonathanGorbutt** [comment]
Any idea how long the release will be?

**Comment by medariox** [comment]
Fixed with 1.4.1, please update.
