### ISSUE TITLE
MedusaInstaller

### ISSUE THREAD

**Issue by JonathanGorbutt** [pymedusa/SickRage#1039]
When using the MedusaInstaller it for some reason wont start Medusa, I can however start the thing manually by going to Directory and starting SickBeard.py

**Comment by medariox** [comment]
What do you mean by "it won't start"? What happens if you open it with the Medusa desktop icon?

**Comment by JonathanGorbutt** [comment]
It hangs for a few seconds then tries to load up the web ui, but fails to connect because its not actually running.

I checked the service and that wasn't running nor will it run it just gets the error below.

![Uploading image.png…]()

**Comment by JonathanGorbutt** [comment]
![image](https://cloud.githubusercontent.com/assets/21015102/18289169/2e671ece-7476-11e6-9755-455d6c2e86a1.png)

**Comment by JonathanGorbutt** [comment]
Managed to figure out the problem seems to be not installing python properly, I noticed lots of files missing in there python folder, so I copied my python folder and replaced it and it works fine.

**Comment by medariox** [comment]
That's quite strange. The installer should automatically download Python, check its integrity and finally install it. Working just fine here with the 64 bit version. Maybe the installer got interrupted somehow during the download/installation?
Anyway, glad you solved it!

**Comment by medariox** [comment]
That's quite strange. The installer should automatically download Python, check its integrity and finally install it. Working just fine here with the 64 bit version. Maybe the installer got interrupted somehow during the download/installation?
Anyway, glad you solved it!
