### ISSUE TITLE
Notifications Save Changes doesn't save 

### ISSUE THREAD

**Issue by themixer2000** [pymedusa/SickRage#1042]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 0.1.4
OS: Centos 7
What you did: 
What happened: Save Changes on bottom of  page under devices has no link will not save or cause logs. Can get it to save changes if you choose for example pushover and change settings and choosing save changes next to test settings. 
What you expected: To Save changes
Logs: none
```
PASTE LOGS HERE
```

**Comment by fernandog** [comment]
@themixer2000 
fixed. please update master
