### ISSUE TITLE
Stats at the bottom do not update until restart

### ISSUE THREAD

**Issue by JonathanGorbutt** [pymedusa/SickRage#1054]
Title say it all but just incase I am talking about this below:

https://i.imgur.com/EYBSrMN.png

Says I have 8 Snatched when infact have none, it wont go away till I restart the Medusa.

I noticed it when I first added my library as well didn't update my total shows until I retarted.

**Comment by medariox** [comment]
Fixed here: https://github.com/pymedusa/SickRage/pull/1057
Thanks for reporting this, will be merged soon.
