### ISSUE TITLE
sqlite3.OperationalError: database or disk is full

### ISSUE THREAD

**Issue by dammed5** [pymedusa/SickRage#1055]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Python Version: 2.7.9 (default, Mar 1 2015, 12:57:24) [GCC 4.9.2]
 Operating System: Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
 Locale: UTF-8
 Branch: master
Commit: pymedusa/SickRage@ ba2d949 

What you did:            
       tried to start sickrage 'service sickrage start'

What happened:
      Job for sickrage.service failed. See 'systemctl status sickrage.service' and 'journalctl -xn' for details.

What you expected:
        sickrage to start

Logs:
```
Sep 09 05:11:31 SHANADOA python[5456]: File "/opt/sickrage/sickbeard/__init__.py", line 1359, in initialize
Sep 09 05:11:31 SHANADOA python[5456]: cache_db_con.action("VACUUM")
Sep 09 05:11:31 SHANADOA python[5456]: File "/opt/sickrage/sickbeard/db.py", line 256, in action
Sep 09 05:11:31 SHANADOA python[5456]: sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
Sep 09 05:11:31 SHANADOA python[5456]: File "/opt/sickrage/sickbeard/db.py", line 108, in _execute
Sep 09 05:11:31 SHANADOA python[5456]: sql_results = self.connection.cursor().execute(query)
Sep 09 05:11:31 SHANADOA python[5456]: sqlite3.OperationalError: database or disk is full
Sep 09 05:11:31 SHANADOA systemd[1]: sickrage.service: control process exited, code=exited status=1
Sep 09 05:11:31 SHANADOA systemd[1]: Failed to start SickRage Daemon.
Sep 09 05:11:31 SHANADOA systemd[1]: Unit sickrage.service entered failed state.
```

**Comment by medariox** [comment]
Your disk is full?

**Comment by medariox** [comment]
Shouldn't error anymore, but only be a warning now.
