### ISSUE TITLE
Collapse button not working in manage episode status page

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#1060]
1) Click expand
2) Click collapse. 
It keep adding "more lines" to the table

@OmgImAlexis

**Comment by fernandog** [comment]
getting
`localhost:80/manage/showEpisodeStatuses [HTTP/1.1 304 Not Modified 16ms]`

**Comment by OmgImAlexis** [comment]
lol someone fucked up and added a class to it to get more episodes.
```
<input type="button" class="pull-right get_more_eps btn" id="305378" value="Collapse">
```

**Comment by OmgImAlexis** [comment]
Fix: https://github.com/pymedusa/SickRage/pull/1085

**Comment by fernandog** [comment]
Thanks!
