### ISSUE TITLE
log_filter='SEARCHQUEUE' and 'SHOWQUEUE' doesn't work

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#1118]
It used to retrieve all threads:

so log_filter by `SEARCHQUEUE` would show:
'SEARCHQUEUE-DAILY-SEARCH'
'SEARCHQUEUE-BACKLOG'
'SEARCHQUEUE-MANUAL'
'SEARCHQUEUE-FORCED'
'SEARCHQUEUE-RETRY'
'SEARCHQUEUE-RSS'

**Comment by fernandog** [comment]
@ratoaq2 we still need to fix this

**Comment by ratoaq2** [comment]
Fixed by #1118

**Comment by fernandog** [comment]
Thanks!
