### ISSUE TITLE
FEATURE REQUEST - See search providers history

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/SickRage#1167]
It would be nice to be able to see a search providers history. what is scraped/cached last 24h or last week or so. To see that it picks up what it is supposed to.

**Comment by fernandog** [comment]
just open `viewlogs` and filter `Search Queue (Daily Searcher)` with `DEBUG`

you will see a bunch of `Unable to match ...` - those are results that not match your library shows

and you will see some `Added RSS item` for items that match a show in your library

**Comment by wimpyrbx** [comment]
did not think of that..! thanks!
