### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: ABC iview

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#1182]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/SickRage@00d5079dec2a8369b281e42c7d53754069a111c6
**Link to Log**: https://gist.github.com/be7cc43e128c5983849fc5d38a70da26
### ERROR
<pre>
2016-09-24 12:17:05 ERROR    Thread-15 :: [00d5079] Missing time zone for network: ABC iview
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
I don't think there's a timezone for this since it's an online site just like netflix, etc. you could use the ACT's timezone which is AEST and is where ABC's headquarters are for iview.

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/SickRage@13b3b09a67ed0e6fe33c1f5ea979cdcf7d18ae00
**Link to Log**: https://gist.github.com/1397b6a8bda96958faf71e38449153a9
### ERROR
<pre>
2016-09-25 20:35:51 ERROR    Thread-15 :: [13b3b09] Missing time zone for network: ABC iview
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato are you going to add this network?

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@a9b215a0250d860b8cd851dc026e5361672f4d1c
**Link to Log**: https://gist.github.com/bde2d2318a40cd21c0bbd3a6b22ce7ce
### ERROR
<pre>
2016-10-31 15:15:10 ERROR    Thread-15 :: [a9b215a] Missing time zone for network: ABC iview
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/6c07fe83a70b2dee3deae32d1e53eabd
### ERROR
<pre>
2017-04-20 08:57:34 ERROR    Thread-20 :: [a011615] Missing time zone for network: ABC1
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by phraymond** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]`
**Operating System**: `Linux-4.9.19-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/8f79e572ebf0998b8b58781369b59457
### ERROR
<pre>
2017-04-20 08:57:34 ERROR    Thread-20 :: [a011615] Missing time zone for network: ABC3
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
