### ISSUE TITLE
Manual subtitle search: scored_subtitles not respecting user's subtitle provider order

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#1228]
sort it is not considering the ordered list: app.SUBTITLES_SERVICES_ENABLED

```python
    return sorted([(s, compute_score(s, video, hearing_impaired=app.SUBTITLES_HEARING_IMPAIRED))
                   for s in subtitles_list], key=operator.itemgetter(1), reverse=True)
```

when subtitles has same score, it should sort by providers order choosed by user

scored_subtitles return this:
[(Subtitle object, 342), (Subtite object, 342)]

the sort is only sorting but itemgetter(1) = score
Need somehow to convert app.SUBTITLES_SERVICES_ENABLED into a dict where key is the order and value provider name, then use this in the sort

**Comment by ratoaq2** [comment]
Fixed by https://github.com/pymedusa/SickRage/pull/1168/commits/d102c2213f143821e4bd659eb948c5c5970f2c17
