### ISSUE TITLE
New Changes

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/SickRage#14]
We really need an issue for all of the core changes we're going to be making so we can keep track of things. That's what this issue will be for.

@pymedusa/administrators @pymedusa/contributors @pymedusa/developers @pymedusa/moderators @pymedusa/owners

**Comment by p0psicles** [comment]
Sorry I don't really understand. You want this to be a discussion thread about architectural/functional/technical changes for the core.js?

**Comment by OmgImAlexis** [comment]
For all of Sickrage, since we're moving over to this repo it'll be a good place to keep things we discuss since IRC chats only stay on there while people are talking meaning anyone that's not on that that time doesn't know what happening.

**Comment by labrys** [comment]
Let's keep discussions as closed topics with the discussion tag to avoid skewing our issue resolution numbers.  When a discussion has ended we can maybe remove the discussion label at that time or something similar.
