### ISSUE TITLE
[ FEATURE ] Improve show selection on Popular page

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#150]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: ALL
OS: ANY
What you did: Added show with show list
What happened: No feedback on if show was added
What you expected: Visual indications showing shows that were added.
Logs: Not applicable

We should enable some method of feedback when adding shows from IMDB and TRAKT lists.  My recommendation is to gray-out the show poster and either remove or change the "ADD SHOW" button.

As for changing the "ADD SHOW" button, I feel there are two ways we could go about doing this.  First we could change it to "REMOVE SHOW" and allow the show to be queued for removal (in case it was selected mistakenly) or to make it toggle the selection of the show and add a "SUBMIT" button to the page.  

The advantages of the ADD/REMOVE method is that as the user adds shows, it begins to pull the data in the background immediately, leading to quicker availability of the shows in the show list.  The disadvantage being that the removal process may present issues with the show attempting to be removed before it has been added and the wasted effort of adding a show just to subsequently remove it.

The advantages of the SELECTIVE method is that a user has better control over show selection with the trade off of the shows not being added until after clicking on the SUBMIT button, delaying addition of the shows.

A related issue with the current show page, is that when revisiting the page, any shows that have not yet been fully added to the shows list still appear on the page.  I think the SELECTIVE method could easily address that by persisting the SELECTION and upon reload, excluding the previously selected items from display.

**Comment by labrys** [comment]
@pymedusa/contributors @pymedusa/developers @pymedusa/support 
Thoughts/suggestions/opinions on this?

**Comment by OmgImAlexis** [comment]
I'd say we queue the metadata if it gets added to the cache while the user is still on the page then once they actually add it they'll see instant feedback with the show already having all of the info we need downloaded.

**Comment by labrys** [comment]
I think that's a great idea.  In fact it can even be a background task to do so before the page is even visited so that any popular shows already have their poster and basic info loaded, then if they are adding them from the ADD NEW page they can be added much quicker.

**Comment by p0psicles** [comment]
I was working on a generic recommended shows template. My idea was to switch the add show with a link to the show, as soon as the show was added. Or a disabled button "Being added" (or something like that), for when you click the "add show" button.

I don't really feel anything for a remove show button. Removing a show, doesn't occur that much. And I think we should not introduce allot of different flows for removing shows.

As for the queuing in background. I don't know about that. It will generate additional load. And some users (for ex. synology or raspberry) don't have that. They already need to have allot of patience. I don't believe it's worth the functionality/performance trade off.
