### ISSUE TITLE
Connection error to getURL https://api.pymedusa.com/news.md

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#154]
@OmgImAlexis what is the new URL?

[b720af2] Connection error to getURL https://api.pymedusa.com/news.md Error: u"error hostname 'api.pymedusa.com' doesn't match either of 'cdn.pymedusa.com', 'www.cdn.pymedusa.com'"

**Comment by OmgImAlexis** [comment]
cdn.pymedusa.com matches the sickrage.github.io repo we have so you'll need to use that. I'm thinking maybe we make a new repo just for CDN stuff, thoughts?

**Comment by fernandog** [comment]
@OmgImAlexis news must be ours! We cant use sickrage's

**Comment by OmgImAlexis** [comment]
@fernandog I'm not sure what you're talking about? I was referring to a repo in this org. https://github.com/pymedusa/sickrage.github.io/

**Comment by fernandog** [comment]
@OmgImAlexis what is the direct url for new.md isntead of `https://api.pymedusa.com/news.md` ?

this url doesn't work anymore. gives a NET::ERR_CERT_COMMON_NAME_INVALID error

**Comment by OmgImAlexis** [comment]
e.g. https://github.com/pymedusa/sickrage.github.io/blob/master/sickrage-news/news.md would be https://cdb.pymedusa.com/sickrage-news/news.md

**Comment by fernandog** [comment]
@OmgImAlexis what about 

https://api.pymedusa.com/favicon-64.png
https://api.pymedusa.com/changelog.md
https://api.pymedusa.com/CHANGES.md

**Comment by OmgImAlexis** [comment]
I don't know how else to explain it... all the files in https://github.com/pymedusa/sickrage.github.io/ are on cdn.pymedusa.com just use the path in the repo to find the URL.

CHANGES.md is https://github.com/pymedusa/sickrage.github.io/blob/master/sickrage-news/CHANGES.md so it'd be https://cdn.pymedusa.com/sickrage-news/CHANGES.md

I'm not sure how else to explain it.

**Comment by fernandog** [comment]
i think i got. sorry!
