### ISSUE TITLE
[ BUG ] Control-clicking manual snatch icon does not open in new tab.

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#170]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Develop/776c6fe6eba66d6368618f09511d681db13e4858
OS: Win 10 and Chrome Browser
What you did: Ctrl-click on manual snatch icon
What happened: Page redirects to manual-snatch page
What you expected: New tab to open with manual-snatch page
Logs: not applicable

**Comment by labrys** [comment]
@p0psicles

**Comment by p0psicles** [comment]
Has never worked like that for the manual snatch link.
I tested using commit: a510b690cab38401ff74c91d6f66328739d937f5

Same issue. I can go further back, but this is just because the default click event is catched.
@OmgImAlexis you know an easy way around this?

**Comment by fernandog** [comment]
i don't think we should allow open in new tab

**Comment by p0psicles** [comment]
Well there is nothing to allow. If the user wants to open 30 tabs, it's his right. We just have to make sure, sr keeps working within reasonable boundaries. What's next? We don't allow the user to put their os in standby?

**Comment by fernandog** [comment]
afaik the manual-snatch its not a "link" its a function that is called and when its finished THEN it redirects

**Comment by p0psicles** [comment]
No it's definitely a link:
https://github.com/pymedusa/SickRage/blob/develop/gui/slick/js/ajaxEpSearch.js#L235

**Comment by OmgImAlexis** [comment]
@p0psicles in js just open a new window with the href of the manual search that the user wants.

https://stackoverflow.com/questions/17130852/detecting-middle-mouse-click-event-jquery

**Comment by p0psicles** [comment]
In dev
