### ISSUE TITLE
[APP SUBMITTED]: retryEpisode() takes exactly 5 arguments (4 given)

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#177]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10240**
Locale: cp1252
Branch: **log-cleanup**
Commit: PyMedusa/SickRage@a84ed40f4d58b1c61caf46c930355df4ba3fa8b7
No Log available with ERRORS:
### ERROR
```
Thread-27 :: [a84ed40] Failed doing webui callback: Traceback (most recent call last):
  File "H:\usr\local\sickrage\sickbeard\webserve.py", line 303, in async_call
    result = function(**kwargs)
TypeError: retryEpisode() takes exactly 5 arguments (4 given)

```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by labrys** [comment]
@fernandog is this from manual snatch changes?

**Comment by fernandog** [comment]
Maybe. Will check it

**Comment by p0psicles** [comment]
https://github.com/pymedusa/SickRage/pull/189/commits
