### ISSUE TITLE
Missing link to Feathub

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/SickRage#184]
Don't know if we can create a copy of the existing one? Else if we're not going to use feathub, we should remove the reference.

**Comment by OmgImAlexis** [comment]
We should remove the reference and just use this repo for features and bugs as we have been.

Maybe make a master list for all features and once the request is "accepted" we then create an actual issue for it and start working on it from there?

**Comment by p0psicles** [comment]
I also don't feel much for the Feathub, as I don't think maybe people or looking at it.
Maybe just use the following prefixes and tags:

[FR] (a users feature request)
[FEATURE] (feature has been accepted, and it's being worked on)

And then the master list, which we use to keep track of the FR's. As soon as a [FR] has been accepted or declined, it's added to he list(s), and the [FR] is closed?

**Comment by ratoaq2** [comment]
I have the same opinion. It's simpler to use prefixes and tags and keep them in the github issue tracker.

**Comment by adaur** [comment]
Since py is not as big as SR was (for the moment!)  I'd say a prefix is enough.

**Comment by fernandog** [comment]
don't forget we can user labels too. better to see and better to filter

**Comment by OmgImAlexis** [comment]
Maybe skip the masterlist and just use the labels. This also means we can easily add a list our site that uses the github api to get all current FRs being worked on and ones suggested easily.

I'd say use `[ FEATURE ]` like we've been doing and use two labels, "Suggested" and something like "Working on" as well as a feature label so people can easily drill down to just what they want to see in the issues.

**Comment by p0psicles** [comment]
Ok, so I think we all agree on using the prefix [FEATURE] with the labels that are already available.

What do we do with the current list of FR's that are on feathub for sickrage? We can't really ignore that right?

**Comment by labrys** [comment]
I think all the previous feature requests could go in a single post with a checkbox list for each item and a link back to the feature request on feathub.  We could also combine similar features from feathub into a single line item with the related links.  We could also use this as a master feature request list for features and append new features to the list to easily review all items feature requests at once.

**Comment by labrys** [comment]
Something like this:

* [ ]  Manual Search: let user choose what to download [ [FH:23](http://feathub.com/SickRage/SickRage/+23) ]
* [ ]  Timeout for snatched episodes. (Basic failed download function) [ [FH:25](http://feathub.com/SickRage/SickRage/+25) ]
* [ ]  Make UI mobile friendly [ [FH:79](http://feathub.com/SickRage/SickRage/+79) ]
* [ ]  Set quality size limits [ [FH:77](http://feathub.com/SickRage/SickRage/+77) ]
* [ ]  Add option for most seeders on torrent search [ [FH:57](http://feathub.com/SickRage/SickRage/+57) ]
* [ ]  Allow to download subtitles again for given episodes [ [FH:81](http://feathub.com/SickRage/SickRage/+81) ]
* [ ]  Ad IMDB as show indexer [ [FH:86](http://feathub.com/SickRage/SickRage/+86) ]
