### ISSUE TITLE
[APP SUBMITTED]: tuple indices must be integers, not str

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#191]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.3-3-osmc-armv7l-with-debian-8.3**
Locale: UTF-8
Branch: **history_fix_nt**
Commit: PyMedusa/SickRage@de18ebdf278728af1f1a01785cbf08da3956cbcc
No Log available with ERRORS:
### ERROR
```
TORNADO :: [de18ebd] API :: tuple indices must be integers, not str
```
---
_STAFF NOTIFIED_: @pymedusa/support  @pymedusa/moderators

**Comment by labrys** [comment]
Fixed in feature branch
