### ISSUE TITLE
[ FEATURE ] Add icon next to provider list for "D" - daily enabled and "B" - backlog enabled

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#199]
We already have the "lock" icon. It would be nice to see which provider has daily enabled and which has backlog search enabled

**Comment by labrys** [comment]
personally i think it would be better to just move the checkbox to this page instead

**Comment by fernandog** [comment]
mr_orange branch had all settings in the provider list and it was a mess to maintain. that's why the second tab was created.

this feature is just to add 2 more icons.

**Comment by labrys** [comment]
@fernandog I'm not suggesting moving all the settings to this page just adding a set of checkboxes to enable each type of search for the provider so you can clearly tell from a single view exactly what is and isn't enabled.

**Comment by p0psicles** [comment]
I think adding controls to the first tab (list of providers) would break current UX. I'm for a subtle icon. But not much more then that.

**Comment by p0psicles** [comment]
@OmgImAlexis what you think? I was thinking of adding a couple of 16x16 icons. But use attributes the mark where they are supposed to be placed. I'l have to look at the current mako. But for ex. adding the attribute backlog-enabled-img, would append the image to the div tag. Will take a small bit of js, but is much cleaner on the html?

**Comment by OmgImAlexis** [comment]
From what I can see it shouldn't take any js just use mako if statments and in angular I'll convert it to `ng-if`.

**Comment by p0psicles** [comment]
This is what I've got now. What ya think?
![image](https://cloud.githubusercontent.com/assets/1331394/14085556/d043c920-f520-11e5-9fc6-bb221236fe9c.png)
