### ISSUE TITLE
[APP SUBMITTED]: Thread-13 :: [fcb0d34] Missing time zone for network: RTÉjr

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/SickRage#236]
### INFO
Python Version: **2.7.10 (default, Oct 23 2015, 18:05:06) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]**
Operating System: **Darwin-15.3.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **split_templates**
Commit: PyMedusa/SickRage@fcb0d3498d39c78fc81231f0aa88ea254a115fca
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [fcb0d34] Missing time zone for network: RTÉjr
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@OmgImAlexis already in here: 
https://github.com/pymedusa/sickrage.github.io/blob/master/sb_network_timezones/network_timezones.txt#L1577

can you confirm you still have the issue?

**Comment by OmgImAlexis** [comment]
I only got it once and I haven't had it before so should we mark this as closed for now?
