### ISSUE TITLE
[APP SUBMITTED]: Thread-16 :: [55af592] No Show Object found for show with indexerID: 305687

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/SickRage#244]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [55af592] No Show Object found for show with indexerID: 305687
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [55af592] No Show Object found for show with indexerID: 305687
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-17 :: [55af592] No Show Object found for show with indexerID: 305687
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [55af592] No Show Object found for show with indexerID: 305687
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-20 :: [55af592] No Show Object found for show with indexerID: 305687
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [55af592] No Show Object found for show with indexerID: 305687
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-19 :: [55af592] No Show Object found for show with indexerID: 305687
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by OmgImAlexis** [comment]
When a show gets removed it should wait for all threads to finish since a background thread could be handling a show that's currently being removed.

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [55af592] No Show Object found for show with indexerID: 305687
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by fernandog** [comment]
@p0psicles need to remove show from queue's. maybe your PR about queue can handle that in the future

**Comment by p0psicles** [comment]
I don't really have a PR that removes shows from queues. Think the cleanest solution here, is to just wait for all queues to finish. But possibly we can stop the daily and backlog, to speed up the process?

**Comment by fernandog** [comment]
I would say to queue show removal. because backlog/daily stop impact all other shows

**Comment by labrys** [comment]
@p0psicles i have an idea for this, when we delete a show add its id to a global list called "recently_deleted".  Then when you get this, see if id is in "recently_deleted" and if not, *then* raise the error.

**Comment by p0psicles** [comment]
Yeah i agree. That would the most simple solution. Also the error doesn't have any impact on the rest of the search. We'll just have to make sure we add it to recently_deleted at the correct moment.

**Comment by labrys** [comment]
@p0psicles you add it to the recently_deleted list as soon as its queued for deletion because you dont care if its actually been deleted yet.
