### ISSUE TITLE
Dev Release 4/3/2016 - Broken Tabbing on Config, Show List loads into tab

### ISSUE THREAD

**Issue by Thraxis** [pymedusa/SickRage#262]
Branch: develop
Commit: b3a926fc3bd251ac73052b41397142ac80c57990

Loaded a Config page all items for all tabs show for every tab.  Show List loads into tab.

**Comment by OmgImAlexis** [comment]
Yep that was my broken PR that needs to be reverted until I can fix the messy js we have.

@labrys can you please revert the "relative url" PR I made?

**Comment by fernandog** [comment]
@OmgImAlexis done

@Thraxis git pull please
