### ISSUE TITLE
Manual Search: table of results disappear while "Reload results" or "Force search"

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#267]
Table of results gets hidden when clicking "Reload results" or "Force search"

**Comment by p0psicles** [comment]
https://github.com/pymedusa/SickRage/pull/278

**Comment by fernandog** [comment]
@p0psicles 
worked! thanks!
Can you make the spin wheel smaller to have the same height of the button?
Also disable the "force search" while search is running to avoid user click twice?
