### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#307]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@89a459923cfb2020bc32aab80527bc8a263731d5
No Log available with ERRORS:
### ERROR
```
18:02:45 ERROR::Thread-14 :: [89a4599] Unable to get error title : 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/logger.py", line 340, in submit_errors
    title_error = re.match(r'^[A-Z0-9\-\[\] :]+::\s*(.*)(?: \[[\w]{7}\])$', ss(cur_error.message)).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
@ratoaq2

**Comment by p0psicles** [comment]
Hmm, assuming the regex will always provide a result?

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **backlog-force-stop**
Commit: PyMedusa/SickRage@3385229f8a0d54019bda23a955c705f47bfc42e1
No Log available with ERRORS:
### ERROR
```
Thread-14 :: [3385229] Unable to get error title : 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/logger.py", line 384, in submit_errors
    title_error = re.match(r'^[A-Z0-9\-\[\] :]+::\s*(.*)(?: \[[\w]{7}\])$', ss(cur_error.message)).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 do you know how to fix this?

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **dedicated-manual-snatch-scheduler**
Commit: PyMedusa/SickRage@2793d9bc3a2ebe018ddcf4d3324b9e0aface945a
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [2793d9b] Unable to get error title : 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/logger.py", line 384, in submit_errors
    title_error = re.match(r'^[A-Z0-9\-\[\] :]+::\s*(.*)(?: \[[\w]{7}\])$', ss(cur_error.message)).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 the hash shouldn't go before the provider name?

```
2016-04-14 12:41:05 INFO     SEARCHQUEUE-FORCEDSEARCH-262407 :: [HDTorrents] :: [ea015c6] Performing episode search for Black Sails
2016-04-14 12:41:05 INFO     SEARCHQUEUE-FORCEDSEARCH-262407 :: [ea015c6] Using manual search providers
```

**Comment by fernandog** [comment]
https://github.com/pymedusa/SickRage/pull/7

**Comment by fernandog** [comment]
@labrys fault change moving the commit hash to the begin of the message lol

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **fixtorrentz2**
Commit: PyMedusa/SickRage@c048786cc1c3b7b6588a67dbc018d69cfabc52be
Link to Log: https://gist.github.com/7f4d51633e9f0190a1c15c320e57f5b2
### ERROR
```
Thread-18 :: [c048786] Unable to get error title : 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/logger.py", line 430, in submit_errors
    title_error = re.match(r'^(?:.*)(?:\[[\w]{7}\]\s*)(.*)$', ss(cur_error.message)).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment]
This is an old version of logger.py and it shouldn't have this issue anymore
