### ISSUE TITLE
[APP SUBMITTED]: Parsing error: Less than 1 bytes read (0)

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#308]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@89a459923cfb2020bc32aab80527bc8a263731d5
No Log available with ERRORS:
### ERROR
```
18:18:22 ERROR::POSTPROCESSER :: [89a4599] Failed to refine video
Traceback (most recent call last):
  File "/home/home/SickRage/lib/subliminal/core.py", line 542, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/home/SickRage/lib/subliminal/refiners/metadata.py", line 32, in refine
    mkv = MKV(f)
  File "/home/home/SickRage/lib/enzyme/mkv.py", line 56, in __init__
    raise MalformedMKVError('Parsing error: %s' % e)
MalformedMKVError: Parsing error: Less than 1 bytes read (0)
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@89a459923cfb2020bc32aab80527bc8a263731d5
No Log available with ERRORS:
### ERROR
```
18:18:21 ERROR::POSTPROCESSER :: [89a4599] Failed to refine video
Traceback (most recent call last):
  File "/home/home/SickRage/lib/subliminal/core.py", line 542, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/home/SickRage/lib/subliminal/refiners/metadata.py", line 32, in refine
    mkv = MKV(f)
  File "/home/home/SickRage/lib/enzyme/mkv.py", line 56, in __init__
    raise MalformedMKVError('Parsing error: %s' % e)
MalformedMKVError: Parsing error: Less than 1 bytes read (0)
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment]
Malformed MKV. It should be reported as error.
Could you double check with some other program if this mkv file contains errors?

**Comment by duramato** [comment]
Don´t know which file it is. Logs role over by the time i notice this

**Comment by ratoaq2** [comment]
This issue doesn't block subtitles search. Now the subliminal.refiners.metadata logger reports those issues as INFO since this commit: https://github.com/pymedusa/SickRage/commit/9d0121b17e014c68ee6bc3addef393b3219d729c
