### ISSUE TITLE
Make manual search like the proper search thread

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#354]
The Proper Search thread unlike any of the "search queue" ones runs along side them.
Making the manual search thread like the proper thread would mean no more queueing which is, imo, a horrible user experience, for an example i've timed mine (starting a manual search with a backlog running and it took ~9 min)
This would mean no killing of threads, no nada, to avoid queuing.
And a  :+1: user lol

**Comment by fernandog** [comment]
need logs

**Comment by p0psicles** [comment]
@duramato do you suggest we separate the "forced search" from the backlog thread. Making it always run in it's own thread? @labrys what do you think? Is that wise?

**Comment by fernandog** [comment]
backlog thead? isnt the search thread?

**Comment by labrys** [comment]
I agree that the manual search should run in it's own thread.  There are some potential issues that may need to be addressed, such as the effect on provider sessions, CPU usage on low-powered devices, etc. but I think it would greatly improve user experience.

**Comment by p0psicles** [comment]
Sure, but then I think we need to agree on pausing or stopping all other search threads when running something from the forcedSearchScheduler thread. Cause then it will be possible to run a daily, backlog, proper and forcedSearch next to each other. Then we're not even talking about the subtitlesFinder thread.

**Comment by p0psicles** [comment]
#395
