### ISSUE TITLE
[APP SUBMITTED]: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/SickRage#360]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-19 :: [55af592] [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by OmgImAlexis** [comment]
There's 4.39 TB of free space on the server.

**Comment by medariox** [comment]
Do you have this issue with develop?

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-18 :: [55af592] [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [75db5cd] Unable to write image to /media/extssd/Shows/The Path/Season 01/The.Path.S01E04.The.Future.720p.WEB-DL.h264-NTb-thumb.jpg - are you sure the show folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/metadata/generic.py", line 707, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [75db5cd] Unable to write image to /media/extssd/Shows/UnREAL/season-all-banner.jpg - are you sure the show folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/metadata/generic.py", line 707, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [75db5cd] Unable to write image to /media/extssd/Shows/UnREAL/season-all-poster.jpg - are you sure the show folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/metadata/generic.py", line 707, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [75db5cd] Unable to write image to /media/extssd/Shows/Outcast/season-all-banner.jpg - are you sure the show folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/metadata/generic.py", line 707, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [75db5cd] Unable to write image to /media/extssd/Shows/Outcast/season-all-poster.jpg - are you sure the show folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/metadata/generic.py", line 707, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [75db5cd] Unable to write image to /media/extssd/Shows/The Catch/Season 01/The.Catch.S01E03.The.Trial.1080p.WEB-DL.h264-BS-thumb.jpg - are you sure the show folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/metadata/generic.py", line 707, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [75db5cd] Unable to write image to /media/extssd/Shows/Horizon/season-all-banner.jpg - are you sure the show folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/metadata/generic.py", line 707, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **season**
Commit: PyMedusa/SickRage@75db5cd3e636e8832404bb25c005f2849ed15ccb
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [75db5cd] Unable to write image to /media/extssd/Shows/Horizon/season-all-poster.jpg - are you sure the show folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/metadata/generic.py", line 707, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
@medariox I can't check at the moment as I'm packing to move.

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [55af592] [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by fernandog** [comment]
@OmgImAlexis need to try in develop branch

**Comment by OmgImAlexis** [comment]
@fernandog this randomly comes up over night I don't really know a way of triggering it and I can't really test the dev branch on my main install at the moment.

**Comment by OmgImAlexis** [comment]
### INFO
Python Version: **2.7.11 (default, Dec 15 2015, 16:46:19) [GCC 4.8.4]**
Operating System: **Linux-4.1.18-unRAID-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@55af59244f853c38812832343f2209fec59bc8de
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [55af592] [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @SickRage/support @SickRage/moderators

**Comment by p0psicles** [comment]
Can you check you'r free inodes? ```df -i``` for that mount?

**Comment by fernandog** [comment]
@p0psicles
Fixed it in develop. Need to reproduce it there. Omg already knows it

**Comment by labrys** [comment]
@OmgImAlexis @duramato Has there been any recurrence of this issue?

**Comment by OmgImAlexis** [comment]
I haven't seen any issues at all.
