### ISSUE TITLE
[APP SUBMITTED]: 18:34:09 ERROR::POSTPROCESSER :: [1cf76ba] No show id found for 'The A' ({'year': 1983})
None

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#374]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10240**
Locale: cp1252
Branch: **develop**
Commit: PyMedusa/SickRage@1cf76bac0801a4f52614ddf64d435fe50086d239
No Log available with ERRORS:
### ERROR
```
18:34:09 ERROR::POSTPROCESSER :: [1cf76ba] No show id found for 'The A' ({'year': 1983})
None
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10240**
Locale: cp1252
Branch: **develop**
Commit: PyMedusa/SickRage@1cf76bac0801a4f52614ddf64d435fe50086d239
No Log available with ERRORS:
### ERROR
```
18:33:20 ERROR::POSTPROCESSER :: [1cf76ba] No show id found for 'The A' ({'year': 1983})
None
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
Series name should be "The A Team" but "Team" is being stripped from the series name.

**Comment by fernandog** [comment]
@labrys using latest medusa develop
