### ISSUE TITLE
Episode snatched with manual search doesn't change its status to snatched in show overview

### ISSUE THREAD

**Issue by medariox** [pymedusa/SickRage#401]
How to reproduce: Search an episode with manual search, snatch it and go back to show page. The episode will be snatched correctly, but the show overview will still show it as non-snatched (can be different status). It may work correctly for some episodes, but if you try a few you will notice it.

In fact the episode status changes correctly (disable JS for proof), but there is some JS code that overwrites the mako code and causes it to show the incorrect status. I nailed it down to this lines of JS code [here](https://github.com/pymedusa/SickRage/blob/develop/gui/slick/js/ajaxEpSearch.js#L61-L63) and [here](https://github.com/pymedusa/SickRage/blob/develop/gui/slick/js/ajaxEpSearch.js#L66). Removing these lines apparently fixes the issue, but I'm unsure if it causes other problems and I'm not even sure what it is exactly supposed to do. 

@p0psicles 
Can you maybe have a look please?

**Comment by p0psicles** [comment]
Yeah i have an idea where this is coming from. Won't be hard to fix.

**Comment by p0psicles** [comment]
@medariox you also wanna do some testing for me?

**Comment by medariox** [comment]
@p0psicles 
Will test https://github.com/pymedusa/SickRage/pull/451 as soon as I get home tomorrow (max the day after tomorrow).

**Comment by p0psicles** [comment]
PR merged
