### ISSUE TITLE
Medusa Discussion Thread

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#402]
This is a general discussion thread for people to ask questions about Medusa.

**Comment by labrys** [comment]
@NicoLeOca Since my comment about discussing Medusa in here or in IRC on Freenode #pymedusa was removed from [SickRage](https://github.com/SickRage/SickRage/issues/1517), I created this general discussion thread.  You can ask any questions in this thread.

**Comment by NicoLeOca** [comment]
Hi,
I'd be interested to know more about Medusa, before deciding to move.
what feature have you developed since you forked?
can I change of branch and use my backup of the other branch?
Do you have a route of development you can share with us?

cheers

**Comment by NicoLeOca** [comment]
sorry I found the others threads... :-/

**Comment by NicoLeOca** [comment]
This branch appears to be the most active at least... ;-)

**Comment by labrys** [comment]
Our master is not very active as late as we haven't had an initial release yet.  Although we are looking to push an initial release to master really soon.  We've added changes to subtitles to improve results, we've added a manual search function so you can select which results you want, and several other features.  We're working on a manual season search as well, a new UI, improved quality detection, and some other features as well.  We still have a lot more planned for the future too.  The master branch can be safely switched to with no issues.  The develop branch, while functional, and the one all of us currently run, needs some database migration scripts added to allow a clean database migration.  I would recommend backing up your database before switching to develop.

**Comment by fernandog** [comment]
@NicoLeOca o principal é poder escolher o que baixar (modo manual). Ele mostra a lista de resultado s encontrados e voce escolhe com base no grupo e seeds.

**Comment by OmgImAlexis** [comment]
@Vodka2014 tvrage support has been added here so sports "should" work.

**Comment by labrys** [comment]
TVMaze support is currently only in the TVMaze branch, but its a high priority to finish it.

**Comment by Vodka2014** [comment]
@OmgImAlexis Thanks I will take a look on my test machine

**Comment by NicoLeOca** [comment]
Migration to the master successfully done
I am looking forward to seeing what's next.
good luck and thanks for what you've done already

**Comment by felipesalomao** [comment]
Please try allow it update subtitle as whatever frequency (each 30 minutes for example).. Before fork was terrible, it could take 8 hours or more..
