### ISSUE TITLE
fatal: No names found, cannot describe anything.

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#408]
On master, as reported in IRC
```
2016-04-17 18:12:10 WARNING  Thread-15 :: [55af592] git describe --abbrev=0 55af59244f853c38812832343f2209fec59bc8de returned : fatal: No names found, cannot describe anything
```

**Comment by labrys** [comment]
@NicoLeOca This is because we don't have an official release yet so there aren't any release tags for git to detect when checking for upgrades.  When we push the initial release to master this should no longer happen, until then it can be safely ignored.

**Comment by NicoLeOca** [comment]
@labrys that's what I thought
thank you for catching it up in the IRC and come over here to let me know

**Comment by fernandog** [comment]
@labrys will this be fixed with `beta` tag?
