### ISSUE TITLE
[APP SUBMITTED]: Thread-15 :: [2e27113] Missing time zone for network: RÚV

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#417]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@2e2711359d05baca0a0a550bd9345177c7725b05
Link to Log: https://gist.github.com/734cede178601fb4d6aaf602441260ed
### ERROR
```
Thread-15 :: [2e27113] Missing time zone for network: RÚV
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
@fernandog or @labrys can we set the reporter to send all timezone issues to a single one so it's easier to handle instead of opening a new issue every single time?
