### ISSUE TITLE
%d format: a number is required, not unicode

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#418]
Branch/Commit: 2e2711359d05baca0a0a550bd9345177c7725b05 @ develop 
OS: Ubuntu 14.04
Locale: pt_PT.UTF-8
Logs: https://gist.github.com/duramato/163711c18b40d0cdb63435c589a3cdd2

@ratoaq2

**Comment by fernandog** [comment]
@duramato can you confirm it was fixed in last develop?
