### ISSUE TITLE
[APP SUBMITTED]: DAILYSEARCHER :: [2e27113] Missing time zone for network: Maretoh

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#419]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@2e2711359d05baca0a0a550bd9345177c7725b05
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [2e27113] Missing time zone for network: Maretoh
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
somethings going on here, thats not a network

**Comment by duramato** [comment]
"this is an user name of one of the contributers at tvdb, could it be getting info wrong?
http://thetvdb.com/?tab=artistbanners&id=396427 "

**Comment by duramato** [comment]
http://thetvdb.com/?tab=series&id=292421 its one of the shows that Maretoh as network
