### ISSUE TITLE
anizb.org sabnzbd can't download from provided url

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/SickRage#431]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
What you did: That sabnzbd starts downloading using the url that's passed from anizb.org.
What happened: Can't download, keeps trying
What you expected:
Logs:
```
NA
```

I know that it doesn't look like an issue with medusa. But I want to be sure, before going with it to sabnzbd.

**Comment by duramato** [comment]
the url points to a nzb so it should work, https://anizb.org/dl/530070/

**Comment by p0psicles** [comment]
It's a combination of using an old python 2.7.6 and the urllib2 used by sab. Need to upgrade somehow to 2.7.11. Always a blast on debian!
