### ISSUE TITLE
Shooter.cn downloading chinese subs as english

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#449]
OS: Ubuntu 14.04
What happened: Subs finder download a chinese subtitle as if it where an english oen
What you expected: To not download them wrong
Logs: https://gist.github.com/duramato/ac7919f5d55935ea7a3559cb235c856b
File name: `Breaking.the.Magicians.Code.Magics.Biggest.Secrets.Finally.Revealed.S01E01.Episode.1.HDTV.XviD-SickRage.avi`  
Original file name: `magics.biggest.secrets.finally.revealed.s01e01.hdtv.xvid.avi`

![image](https://cloud.githubusercontent.com/assets/10121067/14720501/af2d5472-07f9-11e6-9188-7ef974f66bac.png)

actual subtitle https://gist.github.com/duramato/daa88bebd818cc57686023e75e2b2fb1 , and using google transalate they are even the wrong ones.

**Comment by fernandog** [comment]
@duramato need to open an issue in subliminal
