### ISSUE TITLE
Failed to add a searchresult to cache

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/SickRage#45]
Note for myself.

Branch/Commit: manual-search
OS: Windows 7
What you did: started manual search for Fairy Tail S2 2x90 absolute: 265
What happened: It got some results from oznzb
What you expected: It did not download it, assume because not wanted q. But I expect it to be added to Cache.
Logs:
```
14:26:42 DEBUG::SEARCHQUEUE-MANUAL-114801 :: [oznzb] :: [f7d81b7] Search URL: https://api.oznzb.com/api?apikey=**********&maxage=1100&cat=5000%2C5070%2C5080%2C5040&q=Fairy+Tail+90&limit=100&t=tvsearch&offset=0
14:26:47 DEBUG::SEARCHQUEUE-MANUAL-114801 :: [oznzb] :: [f7d81b7] Using cached parse result for: Fairy.Tail.-.90.-.1080p.BluRay.x264.DHD
14:26:47 DEBUG::SEARCHQUEUE-MANUAL-114801 :: [oznzb] :: [f7d81b7] The result Fairy.Tail.-.90.-.1080p.BluRay.x264.DHD doesn't seem to match an episode that we are currently trying to snatch, skipping it
14:26:47 DEBUG::SEARCHQUEUE-MANUAL-114801 :: [oznzb] :: [f7d81b7] Adding item from search to cache: Fairy.Tail.-.90.-.1080p.BluRay.x264.DHD
14:26:47 DEBUG::SEARCHQUEUE-MANUAL-114801 :: [oznzb] :: [f7d81b7] Connection timed out (sockets) while searching oznzb. Error: '_addCacheEntry() takes at least 6 arguments (4 given)'
```

Results are also parsed and saved to cache.
But Fairy Tail S2 90 is parsed as: season: 2, ep: 42??
"[NotWCP].Fairy.Tail.S2.90.(265).-.That's.the.Power.to.Live.[720p].[CEF6CCE2]" 	"2"	"|42|"	"114801"

I expect it to use the tvdb numbering: season: 6, episode: 39 to save to cache.

**Comment by p0psicles** [comment]
@labrys @fernandog Does this has something to do with the new qualities?

**Comment by fernandog** [comment]
@p0psicles need full traceback

**Comment by p0psicles** [comment]
Okay the _addCacheEntry bug is fixed: https://github.com/pymedusa/SickRage/commit/2c814132933e5119f45fe5a067d73b5c972ab6c7

Now need to find out why it's saving 2/42 in cache and not 6/39
