### ISSUE TITLE
[APP SUBMITTED]: [Errno 28] No space left on device: '/media/extssd/Shows/Lip Sync Battle/Season 02/Lip.Sync.Battle.S02E12.Clark.Gregg.vs.Hayley.Atwell.720p.HDTV.x264-ALTEREGO.mkv'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#452]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **gui-cp-sr**
Commit: PyMedusa/SickRage@3ed34a2004b6464d57701187a82ce4ed9afbe175
Link to Log: https://gist.github.com/f4657f55630112f47f00dfd180806acd
### ERROR
```
POSTPROCESSER :: [3ed34a2] [Errno 28] No space left on device: '/media/extssd/Shows/Lip Sync Battle/Season 02/Lip.Sync.Battle.S02E12.Clark.Gregg.vs.Hayley.Atwell.720p.HDTV.x264-ALTEREGO.mkv'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/helpers.py", line 371, in copyFile
    ek(shutil.copyfile, srcFile, destFile)
  File "/home/home/SickRage/sickrage/helper/encoding.py", line 40, in ek
    result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs)
  File "/home/home/SickRage/lib/shutil_custom/__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 28] No space left on device: '/media/extssd/Shows/Lip Sync Battle/Season 02/Lip.Sync.Battle.S02E12.Clark.Gregg.vs.Hayley.Atwell.720p.HDTV.x264-ALTEREGO.mkv'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
Duplicate: https://github.com/pymedusa/SickRage/issues/360

**Comment by p0psicles** [comment]
This error has a different root cause then the other. This is triggered on the os.open, as in the referenced issue it was caused by os.write. You'll have to narrow down your issue using that information. But all in all, it's not a medusa issue, it's really an issue with your filesystem/mount.

http://stackoverflow.com/questions/6998083/python-causing-ioerror-errno-28-no-space-left-on-device-results-32766-h
http://stackoverflow.com/questions/28590344/ioerror-no-space-left-on-device-which-device
http://superuser.com/questions/575611/no-space-left-on-device

Just some links with similar errors.

@pymedusa/developers Is there a way of not accepting these kind of errors here as issues, as it's not a medusa error. The user should be notified in logs, but that's it.

**Comment by duramato** [comment]
Needs to be a warning ping @medariox

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@480ea6529e68aeaafa25a00a3d8d3b576a79c3dc
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [480ea65] Unable to write image to /media/extssd/Shows/Panorama/Season 2016/Panorama.S2016E17.Medicines.Big.Breakthrough.Editing.Your.Genes.HDTV.x264-SickRage-thumb.jpg - are you sure the show folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/metadata/generic.py", line 706, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@480ea6529e68aeaafa25a00a3d8d3b576a79c3dc
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [480ea65] Unable to write image to /media/extssd/Shows/Australian Story/Season 21/Australian.Story.S21E30.What.a.Wonderful.World.HDTV.x264-CBFM-thumb.jpg - are you sure the show folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/metadata/generic.py", line 706, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
@fernandog

**Comment by fernandog** [comment]
@duramato its another issue. will check it
