### ISSUE TITLE
Mako Error during manual search

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#455]
```
File H:/usr/local/sickrage/gui/slick/views/snatchSelection.mako:30, in render_content:
<%block name="content">

NameError: 'episode_history' is not defined
```

**Comment by labrys** [comment]
@fernandog

**Comment by fernandog** [comment]
No history for that show+episode?

**Comment by p0psicles** [comment]
I have opened snatchSelection for a show/episode without any history information before. Didin't get that error.

**Comment by fernandog** [comment]
i can't reproduce. next time submit issue please.

**Comment by labrys** [comment]
@fernandog I created the issue because it wouldnt let me submit it.
