### ISSUE TITLE
[APP SUBMITTED]: Thread-13 :: [f63de39] Missing time zone for network: Sky Sports F1

### ISSUE THREAD

**Issue by Vodka2014** [pymedusa/SickRage#466]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **tvmaze**
Commit: PyMedusa/SickRage@f63de39b8e69dd662ed2e115b4cc6cac1d4d7d75
No Log available with ERRORS:
### ERROR
```
Thread-13 :: [f63de39] Missing time zone for network: Sky Sports F1
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
@Vodka2014 When tvmaze goes live these network timezone issues won't be an issue anymore as tvmaze stores the timezone, unlike tvdb.

**Comment by Vodka2014** [comment]
Ok cool thanks.
