### ISSUE TITLE
Scene Name Issue

### ISSUE THREAD

**Issue by Vodka2014** [pymedusa/SickRage#467]
Branch/Commit: tvmaze / f63de39b8e69dd662ed2e115b4cc6cac1d4d7d75
OS: Synology DSM
What you did: Try To Add Scene Name
What happened: Did Not Save
What you expected: For It To Save
Logs: N / A

Right so WWE Friday Night Smack Down does not want to save the Scene Names as WWE Friday Night Smackdown.

This is tested on WWE RAW as well so seems there is an bug somewhere,

**Comment by fernandog** [comment]
Tvmaze branch is still in progress. Lets see if @p0psicles can fix it.

**Comment by Vodka2014** [comment]
Thanks. So far what i have tested i am happy with. Still got alot of testing to do on the Sports that i watch. :)

**Comment by Vodka2014** [comment]
@p0psicles Let me know if you need any more info. Thanks

**Comment by p0psicles** [comment]
Yeah sure, i don't know anything of sport show series. If you have a couple more shows like this one, I can include them in my tests. They need to be known on tvmaze of course.

**Comment by Vodka2014** [comment]
So the issue here is that the Show Name is : 
Location: WWE SmackDown!
Scene Name: WWE Friday Night SmackDown 

The Scene Name will not save.

**Comment by labrys** [comment]
@Vodka2014 @p0psicles this is because our scene exceptions are stored by tvdbid.  If a show doesn't have a tvdbid it doesn't have a key to store it by.  This is an example of the types of issues I was expecting when we discussed this in IRC.

**Comment by p0psicles** [comment]
Yeah i know. Was planning to create An exception for manual added scene name exceptions, and save/query them by rowid.

**Comment by Vodka2014** [comment]
Ok thanks. So is there any way we can get this updated or steps on how i can add this my self locally since i want to get this working as it has helped me alot with WWE so far.

**Comment by p0psicles** [comment]
Hmm. Yeah it's working locally. But i had to make DB changes. I could commit. But then you cant Go Back to dev or Master until we merge to dev or Master. And id like to have the DB Version incremented for manual search, before i commit this one.

Give it A couple of days and i'll Push to tvmaze branch.

**Comment by p0psicles** [comment]
But that wwe show is also on thetvdb. Doesnt that work for you?

**Comment by Vodka2014** [comment]
Thanks. BUT thetvdb has banned all sport. so what is there is there and what is new does not work. tvmaze is the only site right now that works 100% so does the sportdb but that is another topic.

i am using the tvmaze branch only on my test machine for sport and my prod for the master. so let me know when u push this out.

Also what changes did you make as since we on this topic we might make changes we can make now ....

**Comment by fernandog** [comment]
@Vodka2014 
maybe in future we implement sportsdb or do you think tvmaze is enought ?

**Comment by Vodka2014** [comment]
Well tvmaze as the same naming or similar to thetvdb. sportsdb has different naming all together. 

I think both will be good to have but i will not like to rename over 500 to 1000 episodes of WWE just to match thesportsdb.

**Comment by labrys** [comment]
I think to support sportsdb we might need to approach sports differently.  Maybe something like this:
* Add a sport (e.g. Soccer), league (e.g. NFL), team (e.g. Texas Rangers), etc
* Get a list of events from sportsdb for the sport, league, team, etc.
* Perform string query search for desired event using keywords

**Comment by p0psicles** [comment]
Why? Because there are no scene rules for them?

**Comment by Vodka2014** [comment]
@ p0psicles is it possible if u can commint the changes or if @ labrys can make the changes on tvdbid ?

Just a question since i do not know much about the backend for all of this.

Thanks

**Comment by p0psicles** [comment]
@Vodka2014 I've commited and pushed to the tvmaze branch. Pls try the latest version. Your db version will be incremented, so it will not be possible to move back to another branch, without losing your local db.

**Comment by Vodka2014** [comment]
Thanks. Sorry to be dumb here but the tvmaze branch does not update. how do i get this new version :)

**Comment by p0psicles** [comment]
git fetch --all
git reset --hard HEAD
In the local tvmaze Branch. This wil reset it.

**Comment by Vodka2014** [comment]
So i do this via Putty or Gui sorry for the Q but i need some more guidance on this,

**Comment by p0psicles** [comment]
![image](https://cloud.githubusercontent.com/assets/1331394/14894894/462b4e52-0d76-11e6-8adb-3ffac55b6dbc.png)

Fixed another bug, that might cause it to not load the scene name at startup.
But it saves correct for me now.

I can't find any result tough, but that can also be to to the few providers I have available for testing. Mostly nzb.

**Comment by Vodka2014** [comment]
Right so i got the new version again and now it will not start on my Synology / take ages to start. I also deleted everything and started again.

Will let you know what happens. Thanks for the help :)

**Comment by Vodka2014** [comment]
This is now working BUT there is still an bug

```
2016-04-28 23:47:36 INFO     SEARCHQUEUE-FORCEDSEARCH-803 :: [f63de39] Unable to find a download for: [WWE SmackDown! - 2016 04 21 - Main Event Dean Ambrose & Sami Zayn vs. Chris Jericho & Kevin Owens (London, England, U.K.)]
2016-04-28 23:47:33 INFO     SEARCHQUEUE-FORCEDSEARCH-803 :: [NZBs.org] :: [f63de39] Performing episode search for WWE SmackDown!
2016-04-28 23:47:33 INFO     SEARCHQUEUE-FORCEDSEARCH-803 :: [f63de39] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions.json
2016-04-28 23:47:33 INFO     SEARCHQUEUE-FORCEDSEARCH-803 :: [f63de39] Beginning forced search for: [WWE SmackDown! - 2016 04 21 - Main Event Dean Ambrose & Sami Zayn vs. Chris Jericho & Kevin Owens (London, England, U.K.)]
```

It is not looking for the Scene Names that are added. Also on the site is is "WWE SmackDown 2016 04 21" as the file name.

So some how it needs to tell it to look for Name and not Name + Description for Sports. Any Suggestions ?

**Comment by p0psicles** [comment]
Think it's now using the scene exceptions.

```DEBUG::SEARCHQUEUE-MANUAL-803 :: [oznzb] :: [42ff126] Search string: WWE Smack Down 2016 04 14|apr
08:35:08 DEBUG::SEARCHQUEUE-MANUAL-803 :: [oznzb] :: [42ff126] GET URL: https://api.oznzb.com/api?apikey=**********&maxage=2000&cat=5000%2C5070%2C5080%2C5040%2C5050%2C5030%2C5060&q=WWE+Smack+Down+2016+04+14%7Capr&limit=100&t=search&offset=0 [Status: 200]
08:35:08 DEBUG::SEARCHQUEUE-MANUAL-803 :: [oznzb] :: [42ff126] Search string: WWE SmackDown! 2016 04 14|apr
08:35:11 DEBUG::SEARCHQUEUE-MANUAL-803 :: [oznzb] :: [42ff126] GET URL: https://api.oznzb.com/api?apikey=**********&maxage=2000&cat=5000%2C5070%2C5080%2C5040%2C5050%2C5030%2C5060&q=WWE+SmackDown%21+2016+04+14%7Capr&limit=100&t=search&offset=0 [Status: 200]
08:35:11 DEBUG::SEARCHQUEUE-MANUAL-803 :: [oznzb] :: [42ff126] Search string: WWE Friday Night Smack Down 2016 04 14|apr
08:35:14 DEBUG::SEARCHQUEUE-MANUAL-803 :: [oznzb] :: [42ff126] GET URL: https://api.oznzb.com/api?apikey=**********&maxage=2000&cat=5000%2C5070%2C5080%2C5040%2C5050%2C5030%2C5060&q=WWE+Friday+Night+Smack+Down+2016+04+14%7Capr&limit=100&t=search&offset=0 [Status: 200]
08:35:14 DEBUG::SEARCHQUEUE-MANUAL-803 :: [oznzb] :: [42ff126] Unable to match WWE.Friday.Night.Smackdown.04.07.14.XMW to a show in your database```

I've also set it to a sports show in the show options. Altough still no results. But don't know If I should look into that right now. Maybe if you know of a usecase (specific prov), where it always should give a result for a specific ep, I can test on that. Better for you to come to irc for that.

**Comment by Vodka2014** [comment]
Thanks for this. But for some stupid reason SD does not want to work and HD works. So the 720P Versions are getting found but not the SD versions I.E HDTV.x264.xxx

**Comment by p0psicles** [comment]
Ok, I can't do anything about that, unless you give more info. As you can see, it's detecting SD versions just fine for me. Maybe @duramato or @labrys  know more about this?

**Comment by Vodka2014** [comment]
Thanks alot for all the help on this. I will try to see where it is going wrong or just remove everything and start again.

**Comment by duramato** [comment]
SD file name examples that are not detected?

**Comment by labrys** [comment]
@Vodka2014 `HDTV.x264.xxx` would be `unknown` quality, not `SD` as there is no resolution.

**Comment by Vodka2014** [comment]
Example - "WWE.Smackdown.2016.04.14.HDTV.x264-Ebi" This is classed as TV-SD

**Comment by Vodka2014** [comment]
Question has the Scene names been added for WWE Monday Night RAW ?
