### ISSUE TITLE
[APP SUBMITTED]: list index out of range

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#475]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.6-4-osmc-armv7l-with-debian-8.4**
Locale: UTF-8
Branch: **fix-ms-snatch-status**
Commit: PyMedusa/SickRage@deaaf403bd730069709d4168165a18cc754e89eb
Link to Log: https://gist.github.com/9428e6b1c5251b2c5819d5b712777bf3
### ERROR
```
SEARCHQUEUE-MANUAL-248835 :: [LimeTorrents] :: [21f6532] Unknown exception while searching LimeTorrents. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/search.py", line 548, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/osmc/SickRage/sickrage/providers/GenericProvider.py", line 149, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/osmc/SickRage/sickbeard/providers/limetorrents.py", line 80, in search
    torrent_table = html('table', class_='table2')[0 if mode == 'RSS' else 1]
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
https://github.com/pymedusa/SickRage/issues/473#issuecomment-214371722

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@6ac2d379c3056551bbf6dc6f91aaff5210983201
Link to Log: https://gist.github.com/dfc0db7ed0cb0771ccdc616702795135
### ERROR
```
SEARCHQUEUE-MANUAL-309108 :: [LimeTorrents] :: [6ac2d37] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/limetorrents.py", line 95, in search\n    info = titleinfo[1][\'href\']\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/limetorrents.py", line 95, in search
    info = titleinfo[1]['href']
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
Fixed by https://github.com/pymedusa/SickRage/pull/486

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/9287d8e54dde97009f83b3dd7e370c2f
### ERROR
```
FINDPROPERS :: [Zooqle] :: [881d122] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search\n    peers = cells[6].find(\'div\')\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search
    peers = cells[6].find('div')
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/a049c59d7a0e7b6bc40dc5f1b2535b2b
### ERROR
```
SEARCHQUEUE-BACKLOG-280063 :: [HDSpace] :: [881d122] Unknown exception while searching HDSpace. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/hdspace.py", line 108, in search
    data = data.split('<div id="information"></div>')[1]
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/15d30a7586a1613803d10d157c97f315
### ERROR
```
SEARCHQUEUE-BACKLOG-280063 :: [Zooqle] :: [881d122] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search\n    peers = cells[6].find(\'div\')\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search
    peers = cells[6].find('div')
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/0b348d8dfa389df965368f4d382cccba
### ERROR
```
SEARCHQUEUE-BACKLOG-268960 :: [HDSpace] :: [881d122] Unknown exception while searching HDSpace. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/hdspace.py", line 108, in search
    data = data.split('<div id="information"></div>')[1]
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/aacbc7ca14917f546eaa0e55e17441b3
### ERROR
```
SEARCHQUEUE-BACKLOG-268960 :: [Zooqle] :: [881d122] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search\n    peers = cells[6].find(\'div\')\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search
    peers = cells[6].find('div')
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/1aa7d621bc5d878cfb4362d5bd334572
### ERROR
```
SEARCHQUEUE-BACKLOG-77992 :: [HDSpace] :: [881d122] Unknown exception while searching HDSpace. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/hdspace.py", line 108, in search
    data = data.split('<div id="information"></div>')[1]
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/74786047e0e36dd62ca4034d1e185866
### ERROR
```
SEARCHQUEUE-BACKLOG-77992 :: [Zooqle] :: [881d122] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search\n    peers = cells[6].find(\'div\')\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search
    peers = cells[6].find('div')
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/692f9fbfe889d8a98bbebc2233382a08
### ERROR
```
SEARCHQUEUE-BACKLOG-76372 :: [Zooqle] :: [881d122] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search\n    peers = cells[6].find(\'div\')\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search
    peers = cells[6].find('div')
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
Link to Log: https://gist.github.com/b6abca4c95b14b598c15dc231bf24dd6
### ERROR
```
SEARCHQUEUE-BACKLOG-83755 :: [HDSpace] :: [881d122] Unknown exception while searching HDSpace. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/hdspace.py", line 108, in search
    data = data.split('<div id="information"></div>')[1]
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-83755 :: [Zooqle] :: [881d122] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search\n    peers = cells[6].find(\'div\')\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search
    peers = cells[6].find('div')
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-78847 :: [HDSpace] :: [881d122] Unknown exception while searching HDSpace. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/hdspace.py", line 108, in search
    data = data.split('<div id="information"></div>')[1]
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-78847 :: [Zooqle] :: [881d122] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search\n    peers = cells[6].find(\'div\')\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search
    peers = cells[6].find('div')
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-279357 :: [HDSpace] :: [881d122] Unknown exception while searching HDSpace. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/hdspace.py", line 108, in search
    data = data.split('<div id="information"></div>')[1]
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-279357 :: [Zooqle] :: [881d122] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search\n    peers = cells[6].find(\'div\')\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search
    peers = cells[6].find('div')
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-250793 :: [HDSpace] :: [881d122] Unknown exception while searching HDSpace. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 547, in searchProviders
    forced_search, downCurQuality, manual_search, manual_search_type)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 157, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/hdspace.py", line 108, in search
    data = data.split('<div id="information"></div>')[1]
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@881d1224faaaaecd4228d9572f749044f222fe2a
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-250793 :: [Zooqle] :: [881d122] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search\n    peers = cells[6].find(\'div\')\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/zooqle.py", line 121, in search
    peers = cells[6].find('div')
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@480ea6529e68aeaafa25a00a3d8d3b576a79c3dc
Link to Log: https://gist.github.com/a148c920416539d7f354e8de909dcf2a
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: [480ea65] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/sickbeard/providers/torrent/html/transmitthenet.py", line 156, in parse\n    seeders = try_int(cells[8].text.strip())\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrent/html/transmitthenet.py", line 156, in parse
    seeders = try_int(cells[8].text.strip())
IndexError: list index out of range
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
