### ISSUE TITLE
can't switch to develop branch

### ISSUE THREAD

**Issue by felipesalomao** [pymedusa/SickRage#498]
Medusa Info:	Branch: master
Commit: 55af59244f853c38812832343f2209fec59bc8de
Version: fatal: No names found, cannot describe anything.
 Python Version:	2.7.11 (default, Mar 28 2016, 10:46:06) [GCC 5.3.0]
 SSL Version:	OpenSSL 1.0.2g 1 Mar 2016
 OS:	Linux-3.4.6-armv5tel-with-glibc2.4
 Locale:	en_US.UTF-8

Hi, when i select develo branch on http://192.168.1.113:7073/config/general/ and then click on checkout branch, i get error: "can't switch branch as this will result in database downgrade sickrage"

Actually i am on master. How solve it ? Thanks

**Comment by fernandog** [comment]
you will have to wait a few days when we release to master.
sickrage branch upgraded DB without actually change anything in DB

**Comment by felipesalomao** [comment]
Ok, so now its pyMedusa problem due wasnt relased master ?!

**Comment by fernandog** [comment]
Yes. We need to fake upgrade db too

**Comment by felipesalomao** [comment]
ok.. will just wait..
this information on " Help & Info" is because of that ? 
Version: fatal: No names found, cannot describe anything.

**Comment by fernandog** [comment]
Ignore that

**Comment by felipesalomao** [comment]
Ok.. Thank you

**Comment by felipesalomao** [comment]
I got this warning in log, this its because of it too ?

```
2016-04-27 18:15:50 Thread-13 :: [55af592] "/Apps/bin/git" describe --abbrev=0 55af59244f853c38812832343f2209fec59bc8de returned : fatal: No tags can describe '55af59244f853c38812832343f2209fec59bc8de'.
Try --always, or create some tags.
```

**Comment by fernandog** [comment]
You can also ignore.

**Comment by felipesalomao** [comment]
Ok

**Comment by fernandog** [comment]
@felipesalomao we released to master. please try
