### ISSUE TITLE
Currently there is no indication when a show has a per season exception

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/SickRage#50]
I'm going to implement an indication for shows which have a per season name exception.
Currently the only way to know there is any, is by tracking the debug logs, or digging in the db files.

I'm starting this issue to discuss the solution. If there are any other indicators that are missing, let me know!

Branch/Commit: SickRage master/dev
OS:
What you did: Opened the shows displayShow
What happened: No indication which (xem) per season exceptions are configured
What you expected: An indication
Logs:
```
Not needed
```

quick mockup:
![image](https://cloud.githubusercontent.com/assets/1331394/13381452/f1a02e90-de5c-11e5-9c92-808b4087ae37.png)

**Comment by duramato** [comment]
Now there are our scene exceptions per season too, perhaps support them too?

**Comment by OmgImAlexis** [comment]
Do we even have a way to add/edit per season exceptions apart from the JSON file? Might need to add that as well.

**Comment by duramato** [comment]
@OmgImAlexis there is not, and agree

**Comment by p0psicles** [comment]
@duramato are you talking about the "custom" field in the scene_exceptions table? If so, how do we support that besides that it's in the db?

**Comment by duramato** [comment]
I dont know how it works, but i do know we support season exceptions from xem and our json

**Comment by p0psicles** [comment]
Ok, got the xem exceptions working.
![image](https://cloud.githubusercontent.com/assets/1331394/13399855/85c8cee4-df05-11e5-9203-366a04a308d9.png)

In case of fairy tail it's only showing the xem icon, for indexer_seasons 5,6,7

**Comment by p0psicles** [comment]
Should I do the https://raw.githubusercontent.com/pymedusa/sickrage.github.io/master/scene_exceptions/scene_exceptions.json in one go? Or keep it for a separate PR?

**Comment by p0psicles** [comment]
Never mind, got it like this: 
![image](https://cloud.githubusercontent.com/assets/1331394/13405034/e71224e0-df1c-11e5-88cf-e7c3541d4b23.png)

**Comment by p0psicles** [comment]
https://github.com/pymedusa/SickRage/tree/thexem-per-season-indication
