### ISSUE TITLE
No warning/messages when fails to removing show from traktlist when show was remove from Medusa library

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#517]
TraktRequest doesn't return True/False so Medusa doesn't know the request was sent ok or not

@p0psicles as you are rewriting it maybe you can handle a return True/False when calling trakt requests

So next trakt check it adds show back again

**Comment by p0psicles** [comment]
Is this related to: https://github.com/pymedusa/SickRage/issues/518?

**Comment by fernandog** [comment]
No. One thing is that is missing a checl of the request were ok (this)

The other is an issue. Who developed code forgot to also remove episodes. @thraxis confirmed issue 518 in the SickRage branch. But nobody fixed.

**Comment by fernandog** [comment]
@p0psicles i think trakt shouldn't use CACHE (not sure if it really use). I say this because I removed show from watchlist directly from trakt but medusa added back again a few minutes later

**Comment by p0psicles** [comment]
Did you try the recommended list branch?  From memory think it was fixed in the fix-trakt-lib branch.

**Comment by fernandog** [comment]
I didn't. but how to make sure the GET methods used in trakt don't use cache?

**Comment by labrys** [comment]
The requests library does not cache results unless you specifically impement it.
