### ISSUE TITLE
Removing show from library removes it from trakt watchlist but doesnt remove episodes from traklist

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#518]
Show is removed from trakt watchlist (after removing show from medusa library), BUT episodes don't get removed from trakt watchlist, so next trakt sync, it will re-add show because there is episodes in watchlist.
@p0psicles

**Comment by p0psicles** [comment]
I'll have to add a list of episode objects to the 
> sync/collection/remove
url.

These should be passed as a list of objects as described below. It's adviced to use the trakt id. In this example 1061. But we don't have that in db. Should I just get a complete list of trakt episode id's for the show that's deleted? And try to remove them all?

Alternative can be just pass the tvdb episode id. But with future indexers in mind, i'd prefer using the trakt id.
```
"episodes": [
      {
        "ids": {
          "trakt": 1061,
          "tvdb": 1555111,
          "imdb": "tt007404",
          "tmdb": 422183,
          "tvrage": 12345
        }
      }
    ]
```

**Comment by ratoaq2** [comment]
@p0psicles @fernandog 
Can this one be closed?
