### ISSUE TITLE
displayShow.mako and snatchSelection.mako broken in Firefox

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#525]
@wimpyrbx as we talked. In Chrome it works

![image](https://cloud.githubusercontent.com/assets/2620870/14970491/a248b7d4-109f-11e6-9197-cecc4282cb52.png)

**Comment by OmgImAlexis** [comment]
@fernandog just add this to the css file.

````
.summaryTable tr td {
    word-break: break-all;
}
````

**Comment by OmgImAlexis** [comment]
Actually another fix would be to just add a space after the comma like `german, french` as that'd make allow the browser to auto break the line since it wouldn't treat the whole line as a single word anymore.
