### ISSUE TITLE
PostProcessor doesn't PP propers first. It doesn't have any order now

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#532]
It should PP propers first and discard non-proper. Or leave behind and give a warning to user.

**Comment by OmgImAlexis** [comment]
Wouldn't that mean you end up with a bunch of files left over since it wouldn't delete the nuked version?
If it processes the nuked and then PROPER the nuked one gets deleted/replaced.

**Comment by p0psicles** [comment]
I have a feeling this will just be one of the downsides of using the Postprocessor, and not using a triggered PP like nzbToMedia. When it's triggered, there just PP'd in order right?

Personally I think there should be a limit, as too how much intelligence we build into the PP. Can you describe a couple of user stories, with different outcomes? From the description of this issue, it's not clear too me, as to what can go wrong.

**Comment by duramato** [comment]
Post proceds scrits for torrenr arent thay good.
*Daily snatches torrent ,gets downloaded and PP, proper gets snatched and pp fine.
*Daily snatches torrent, proper gets snatched ,normal gets downloaded and PP, when the proper is going to be PP it is already as " Downloaded" and as generally propers can have a smaller size wont be PPed
*Daily snatches , Gets PP, Proper snatches, PP runs and PP the non proper becouse it sees a snatched status and torrents are all in downloaded in the smae folder and seeding with links,proper will get PP or not if its of less size.
*Daily snatches proper ,gets PP, end
 Think thats most of the cases

**Comment by fernandog** [comment]
5) Proper and non proper are snatched. Both finihes download and are in PP folder. When PP run it can PP  any one first.

**Comment by fernandog** [comment]
6) Proper finishes download first. Gets PP. Then non proper finishes. PP error already processed (should be deleted)
