### ISSUE TITLE
Too many requests to nzb caps while editing providers settings

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#533]
It should only query/update categories in the "custom nzb providers" tab and not each provider order change for example

```
13:23:17 DEBUG::Thread-15 :: [26d7361] GET URL: https://api.nzbgeek.info/api?apikey=**********&t=caps [Status: 200]
13:23:17 DEBUG::Thread-17 :: [26d7361] GET URL: https://www.usenet-crawler.com/api?apikey=**********&t=caps [Status: 200]
13:23:21 DEBUG::Thread-18 :: [26d7361] GET URL: https://api.oznzb.com/api?apikey=**********&t=caps [Status: 200]
13:23:48 DEBUG::Thread-15 :: [26d7361] GET URL: https://api.nzbgeek.info/api?apikey=**********&t=caps [Status: 200]
13:23:49 DEBUG::Thread-18 :: [26d7361] GET URL: https://www.usenet-crawler.com/api?apikey=**********&t=caps [Status: 200]
13:23:52 DEBUG::Thread-17 :: [26d7361] GET URL: https://api.oznzb.com/api?apikey=**********&t=caps [Status: 200]
13:24:01 DEBUG::Thread-17 :: [26d7361] GET URL: https://api.nzbgeek.info/api?apikey=**********&t=caps [Status: 200]
13:24:01 DEBUG::Thread-18 :: [26d7361] GET URL: https://www.usenet-crawler.com/api?apikey=**********&t=caps [Status: 200]
13:24:15 DEBUG::Thread-17 :: [26d7361] GET URL: https://api.nzbgeek.info/api?apikey=**********&t=caps [Status: 200]
13:24:16 DEBUG::Thread-18 :: [26d7361] GET URL: https://www.usenet-crawler.com/api?apikey=**********&t=caps [Status: 200]
13:24:20 DEBUG::Thread-16 :: [26d7361] GET URL: https://api.oznzb.com/api?apikey=**********&t=caps [Status: 200]
13:24:20 DEBUG::Thread-15 :: [26d7361] GET URL: https://api.oznzb.com/api?apikey=**********&t=caps [Status: 200]

```

**Comment by p0psicles** [comment]
I agree this could be enhanced. Only discussion here is, that the entire provider code regarding newznab is candidate to be rewritten all together. And that has higher prio IMHO then this bug.

My idea was to fix the newznab providers in stages:
1. Separate the newznab providers in a template component and the newznab providers itself. Removing the newznab_data setting. Partly every NN provider is already saved in a config section, but it's missing properties.
For ex. this is a current nzbgeek config:
```
[NZBGEEK]
nzbgeek = 0
nzbgeek_search_mode = eponly
nzbgeek_search_fallback = 0
nzbgeek_enable_daily = 0
nzbgeek_enable_backlog = 1
nzbgeek_enable_manualsearch = 0
```
As an examle it will also get the api key.

2. Remove the configProviders.js, and replace it with core.js code. Goal is to process newznab providers similar to the static providers, but use rest calls to the CRUD. For this we'll use mostly jquery.append / remove etc.

3. Rewrite the providers page in Angular.

**Comment by fernandog** [comment]
Agree. For that we need a setting to know those are NZN providers. All listed providers are torrent.

I think this fix is easy. Just remove the call to populate nzv when saving settings. Last line of configProviders.js but im not sure.

**Comment by p0psicles** [comment]
@fernandog can this be closed now?
