### ISSUE TITLE
API shows as "TODAY" but in "schedule" page it shows as "wanted"

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#535]
API doesn't take in count airtime, only airdate

So results from API are different from /schedule

This PR was started to fix this but dev didnt continue:
https://github.com/SiCKRAGETV/SiCKRAGE/pull/2558

**Comment by OmgImAlexis** [comment]
This is todo with APIv1 which is now not being supported or worked on. Closing.

**Comment by fernandog** [comment]
But issue will still exist in v2 right?
