### ISSUE TITLE
[ META ] Please sign all commits with a GPG key

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/SickRage#538]
Since Github now shows if a commit has been signed with a GPG key it's probably a good time to start moving towards having all commits and all tags signed. If you need any help setting up a GPG key and git there's a few tutorials on the [blog post](https://github.com/blog/2144-gpg-signature-verification) and I can help if need be.

@labrys which group contains everyone so I don't have to tag all of our groups every time I open an issue like this.

@pymedusa/administrators @pymedusa/contributors @pymedusa/developers 
@pymedusa/super-awesome-guys

**Comment by duramato** [comment]
What is its use? Everyone uses their own acc for their commits already afaik

**Comment by OmgImAlexis** [comment]
Yes but there's nothing that actually proves the commits made from your account are yours or the commits with your username/email were made by you. This solves that and once setup won't require anything more than entering a password before committing but means that every single commit pushed to this repo is signed to prove who actually made the changes.

**Comment by duramato** [comment]
If , big if :p , a commit reaches the repo not made by me github account is if it gpt breached etc and that could be solved by a 2FA.
This is git so you can check what commit changed
And what can garantee somone gets or doesnt your key(s) :/

**Comment by OmgImAlexis** [comment]
Yes this is git but right now I could make any changes I wanted and add your username/email and push to this repo. There's nothing at all that shows that you or I made that change but if every commit was signed and I pushed a change that had your username/email without your key then we'd know it was a fake commit.

Unless you're really bad at using a computer I can't see anyone getting your keys, I currently have mine on my laptop with my [public key](https://keybase.io/OmgImAlexis/key.asc) on [keybase](keybase.io/omgimalexis). I plan on moving my private key to a Yubikey once I've got some spare time meaning someone would need access to not only my laptop but also the Yubikey usb to sign commits with my key.

**Comment by duramato** [comment]
My passwords are hashes the probability of someone guessing them is "inpossible" so they either would probably need to mitm me or torture me lmao. Thats what i meant with it becouse if they get the hash used as pass , which is giberish and non human readble words is probably in the same probability of guessing the keys.
Dont have anything agaist people signing the commits, just dont see a need as it only tells you it wasnt me that pushed the bad code but i got hacked/etc .
Doesnt bring extra protection

**Comment by labrys** [comment]
@duramato Actually theres a utility to rewrite commit history that you don't need to have any information about the user except account name.  Of course you still would have to have push/merge rights to the repo to merge it.

**Comment by labrys** [comment]
Do I think this is important or a high priority? No. But what does it hurt to set up GPG?  There are a couple (admittedly rare) scenarios where I see this as not being possible (one of which applies to me) but those would be the exception rather than the rule.

**Comment by OmgImAlexis** [comment]
Since we're now using Github's squash merge this isn't possible as it rewrites the commit.
