### ISSUE TITLE
Viewlog objects overlapped

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#540]
@OmgImAlexis 
code of the page. looks like the class h2footer is overlapping class header
to reproduce just resize browser size

```html
<%block name="content">
% if not header is UNDEFINED:
    <h1 class="header">${header}</h1>
% else:
    <h1 class="title">${title}</h1>
% endif

<div class="h2footer pull-right">Minimum logging level to display: <select name="minLevel" id="minLevel" class="form-control form-control-inline input-sm">
    <%
        levels = LOGGING_LEVELS.keys()
```

![image](https://cloud.githubusercontent.com/assets/2620870/15053918/53146436-12db-11e6-9a0c-34eee0c23b32.png)

**Comment by OmgImAlexis** [comment]
That's because of the weird `pull-right` thing we do. Can we have a milestone for Bootstrap v4? Things like this would be best to just leave for now until we move to Bootstrap v4 as there's new flexbox layouts.

**Comment by fernandog** [comment]
@OmgImAlexis can't we fix this as this affects user experience in mobile?

sure bootstrap can fix in the furure. but we need before that

**Comment by OmgImAlexis** [comment]
I'm not too sure, the best I'd say for now would be to use media queries and just hide it or use margins to move it when on mobile.
