### ISSUE TITLE
Statusline pr season

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/SickRage#575]
http://www.fshare.it/image.jpeg?i=h3146280410

image shows what's suggested.
layout and what info is on that line can be discussed of course.

some suggestions are:
* number of episodes downloaded
* total size of episodes downloaded
* average size of episodes? to identify if any episode differs very much from average
* for example count of x264 vs x265 and other codecs counters (needs that info in the db of course)
  see https://github.com/pymedusa/SickRage/issues/577

**Comment by wimpyrbx** [comment]
important note here. if there is an episode S0XE03E04 for example. do not count the size twice for the total season size.

**Comment by wimpyrbx** [comment]
http://www.fshare.it/i.php?i=h3146280410

here is a crude example of what i mean. i do believe it could be even better to move the sizes in relevance to the Size column already used for episodes etc, but still it's an example.

**Comment by Thraxis** [comment]
I'm holding off on submitting this as a PR I haven't put it into a branch on my Git yet either.  But I have the basic piece of this done now:

![image](https://cloud.githubusercontent.com/assets/1131905/17049902/de34fd4a-4fa4-11e6-9d22-08ed7c7bbf12.png)

**Comment by Thraxis** [comment]
This is currently in Develop now
