### ISSUE TITLE
No module named future dont let pymedusa start

### ISSUE THREAD

**Issue by felipesalomao** [pymedusa/SickRage#589]
Hi it was running without problem here until 3 days ago, but after i restarted it, i wasnt able to start again, then used putty to see what is happening..

See details above: 
```
 /etc/init.d/sickbeard-tvrage.sh restart
armv5tel
Restarting SickBeard-TVRage
armv5tel
Shutting down SickBeard-TVRage...
SickBeard-TVRage is not running?
armv5tel
SickBeard-TVRage prestartup checks...
 Checking for git...  Found!
Looking for /usr/bin/python2.7
Looking for /usr/local/bin/python2.7
Looking for /opt/bin/python2.7
Looking for /Apps/opt/bin/python2.7
Looking for /opt/QPython2/bin/python2.7
Found Python Version 2.7.5 at /usr/local/bin/python2.7
Updating SickBeard-TVRage
HEAD is now at d491854 Update PULL_REQUEST_TEMPLATE.md (#504)
Already up-to-date.
Starting SickBeard-TVRage
Traceback (most recent call last):
  File "SickBeard.py", line 46, in <module>
    from __future__ import unicode_literals
ImportError: No module named __future__
```

I already tried all to fix it.. Any suggestion how solve this problem ?

**Comment by labrys** [comment]
Sounds like your python path variable got messed up.  Have you tried rebooting since?

**Comment by felipesalomao** [comment]
Teste, Tried Allen including reboot. Algo Tried reinstall phynton and
optware.

I use qnap nas. It was working normally then for no reason It started
having those kind oferece problems.

Em terça-feira, 17 de maio de 2016, Labrys of Knossos <
notifications@github.com> escreveu:

**Comment by felipesalomao** [comment]
I was able to make it work again following bellow instructions:
http://forum.qnap.com/viewtopic.php?f=223&t=118366&sid=6573ea37e4454afccb6f777d7688b1d2

I it was some unknow trouble in python or optware error..

**Comment by labrys** [comment]
@felipesalomao I'm really glad to hear you got this sorted out.  I had done some more research into it and everything I read all pointed to an invalid python path.  I'm thinking something may have altered your python installation (either another application installed a python version and updated the path variables, or something just got corrupted).  I registered for the QNap forum and reading the procedures you followed seems to support that assumption.
