### ISSUE TITLE
Tornado is being spammed with requests.

### ISSUE THREAD

**Issue by labrys** [pymedusa/SickRage#593]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Current develop
OS: Win 10
What you did: Enabled `logging.basicConfig` to see tornado logs (see #592)
What happened: With no UI interaction, tornado is being spammed with requests.
What you expected: No, or minimal, tornado requests without interaction.
Logs:
```
INFO:tornado.access:200 GET /ui/get_messages (127.0.0.1) 2.00ms
INFO:tornado.access:200 GET /ui/get_messages (127.0.0.1) 2.00ms
INFO:tornado.access:200 GET /ui/get_messages (127.0.0.1) 1.00ms
INFO:tornado.access:200 GET /ui/get_messages (127.0.0.1) 2.00ms
INFO:tornado.access:200 GET /ui/get_messages (127.0.0.1) 2.00ms
INFO:tornado.access:200 GET /ui/get_messages (127.0.0.1) 2.00ms
INFO:tornado.access:200 GET /ui/get_messages (127.0.0.1) 1.00ms
INFO:tornado.access:200 GET /ui/get_messages (127.0.0.1) 2.00ms
INFO:tornado.access:200 GET /ui/get_messages (127.0.0.1) 2.00ms
INFO:tornado.access:200 GET /ui/get_messages (127.0.0.1) 2.00ms
```
In addition Manual Search spams tornado with requests even after the search has long-since terminated.

**Comment by p0psicles** [comment]
We already knew this. Thats what the websocket pr is for.

**Comment by labrys** [comment]
@p0psicles yeah forgot about that... was looking into some UI lag issues.
