### ISSUE TITLE
today's update fail - can't access to anything - have to reinstall

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#614]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: last stable
OS: synology last version
What you did: update
What happened: failed and I don't have access to any parameter; the top is just blank
What you expected: to work
Logs:
https://gist.github.com/NicoLeOca/5ccf233b2cd52892687df6b479723778
```
PASTE LOGS HERE
```

**Comment by NicoLeOca** [comment]
I suspect it's because my Git package wasn't uptodate.

**Comment by fernandog** [comment]
@NicoLeOca still having issues?

**Comment by NicoLeOca** [comment]
Hi,
Everything is ok now.
I wasn't able to access any settings
only a full restart of the package worked

I got this warning now:
2016-05-23 13:48:17 Thread-16 :: [d707b2b] git describe --abbrev=0 d707b2b220b91f1eb554b9b0523eb2c37d67afe6 returned : fatal: No annotated tags can describe 'd707b2b220b91f1eb554b9b0523eb2c37d67afe6'.
However, there were unannotated tags: try --tags.

**Comment by labrys** [comment]
From the logs it looks like there was an issue while checking out the nzbtomedia submodule.  As for the tags, a release has now been tagged so let me know if you still get that warning.

**Comment by NicoLeOca** [comment]
Hi @labrys 
I don't have the warning anymore about the release tag
Thank you

**Comment by NicoLeOca** [comment]
@labrys 

actually; it isn't fixed
2016-05-24 18:06:58 Thread-18 :: [d707b2b] git describe --abbrev=0 d707b2b220b91f1eb554b9b0523eb2c37d67afe6 returned : fatal: No annotated tags can describe 'd707b2b220b91f1eb554b9b0523eb2c37d67afe6'.
However, there were unannotated tags: try --tags.

**Comment by labrys** [comment]
@NicoLeOca Could you try checking for updates to see if you get the error again?

**Comment by NicoLeOca** [comment]
@labrys not at the moment
I cleared the logs, checked for updates but nothing appears.
but it did the same 14 hours ago.

**Comment by labrys** [comment]
Ok, I think I may have resolved the issue.  The tag was applied to the beta branch when released.  I have added a tag to the master branch now.

**Comment by NicoLeOca** [comment]
I don't have a warning about it anymore

**Comment by medariox** [comment]
Great to hear, will close this as it seems to be solved.
