### ISSUE TITLE
seedbox integration

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#627]
Guys,

Medusa is installed on my local NAS.
I use Usenet locally (thanks to SSL encryption) and a distant seedbox (sdedi.com) to protect my IP and get proper upload bandwith.
However, while my local is fully nzbget is fully integrated into Medusa, I got to manually dl with my seedbox what's not available on Usenet.

Do you know a way to integrate a distant seedbox in my local Medusa?
I am also opened to change of seedbox provider if necessary.

Cheers

**Comment by p0psicles** [comment]
It's already possible to integrate a seedbox with medusa. Pay us a visit on irc, and maybe we can come up with a solution?
