### ISSUE TITLE
PP deletes syncthings config file

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#675]
Hi,

the PP folder is a destination folder for a synchronisation with syncthing.
Syncthing creates a local file with the configuration inside.
The file is deleted by PP every single time.

Do you know how to avoid it, please?

Cheers

**Comment by labrys** [comment]
Possibly move the PP folder to a subfolder within the sync folder?

**Comment by NicoLeOca** [comment]
can't do that as the syncfolder isn't the only source of episodes for PP.
the syncfolder has to be a subfolder of the PP folder (and not the other way round).
otherwise syncthing will sync everything, including other sources.
not sure I am clear

**Comment by p0psicles** [comment]
Play with access right? Maybe use different users for medusa and syncthing? In a way that the configuration file can't be removed?

**Comment by NicoLeOca** [comment]
just tried to restrict access to Medusa
but it changed the rights on its own despite it says it didn't.
the file is gone.
very strange

Postprocessing results
Processing folder /volume1/Download Syno/dst
Feature 'postpone postprocessing if no subtitle available' is enabled
PostProcessing Path: /volume1/Download Syno/dst
PostProcessing Dirs: ['Seedbox']
PostProcessing Files: []
PostProcessing VideoFiles: []
PostProcessing RarContent: 
PostProcessing VideoInRar: 
Processing folder Seedbox
Processing folder /volume1/Download Syno/dst/Seedbox/The.Mindy.Project.S04E22.Princeton.Charming.720p.HULU.WEBRip.AAC2.0.H264-NTb[rarbg]
Found temporary sync files: ['.syncthing.The.Mindy.Project.S04E22.Princeton.Charming.720p.HULU.WEBRip.AAC2.0.H.264-NTb.mkv.tmp'] in path: /volume1/Download Syno/dst/Seedbox/The.Mindy.Project.S04E22.Princeton.Charming.720p.HULU.WEBRip.AAC2.0.H264-NTb[rarbg]
Skipping post processing for folder: /volume1/Download Syno/dst/Seedbox/The.Mindy.Project.S04E22.Princeton.Charming.720p.HULU.WEBRip.AAC2.0.H264-NTb[rarbg]
Processing folder /volume1/Download Syno/dst/Seedbox
Found unwanted files: ['.stfolder']
Deleting file: .stfolder
Changing ReadOnly Flag for file: .stfolder
Cannot change permissions of /volume1/Download Syno/dst/Seedbox/.stfolder: error 1 : Operation not permitted
Successfully processed
I did encounter some unprocessable items: 
[/volume1/Download Syno/dst : Syncfiles found]

**Comment by NicoLeOca** [comment]
it's getting better, the logs doesn't display the reality.
I left the right to change permissions of the file to Medusa...

That's fixed now

thanks for your help!

**Comment by labrys** [comment]
Possibly move the sync PP folder to a subfolder within the sync folder and then symlink the sync PP as a subdirectory of your actual PP folder.

**Comment by NicoLeOca** [comment]
That could be an option, maybe more complicated.

on my synology setting up permissions was easy, as sickrage-custom is an identified user already.

thanks Labrys, you're the one who made me aware of syncthing to get my stuff back from my SB

**Comment by medariox** [comment]
I think the issue can be considered solved, if not, please let me know.
