### ISSUE TITLE
Wrong parameter name in API builder

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#681]
Parameter shows as `delete_files` but it is `delete_on`

**Comment by p0psicles** [comment]
The api is not not the same as the webserve call.
For example the api call accepts the param for the directory that needs to be processed, is provided as "path" in the api, and "proc_dir" for the regular route. Sure we could allign these, but then we'd break the api, or the route. So this is more a todo for refactoring then really a bug.

**Comment by fernandog** [comment]
sure. let's leave for later as all the other things.

**Comment by p0psicles** [comment]
I have to correct. Didn't notice it was added recently to the api.
The param was never used before, so labrys choose to rename it now, as it will be harder to rename it when clients have implemented it.

Also it has been added (as delete_on) and renamed (to delete_files) before any of the changes went into master. So we're good here.

**Comment by fernandog** [comment]
again: my point is: rename all or rename none.

**Comment by labrys** [comment]
@fernandog Agreed, they should all be renamed for consistency.  This was left like this because the webserve params are back-end only and isn't exposed to the user.  The UI is changed here to avoid having the UI change on the user when the back-end gets refactored to match.

**Comment by labrys** [comment]
I'm closing this as the API command is fine.  Also before changing `delete_on` in webserve, nzbToMedia would need to be updated as it calls it directly.
