### ISSUE TITLE
Wrong seed sorting

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#717]
Manual search is showing wrong sorting for seeds
last develop
@duramato 

![image](https://cloud.githubusercontent.com/assets/2620870/16414605/f76001dc-3d0e-11e6-8d30-a8622e82939d.png)

**Comment by p0psicles** [comment]
@fernandog, that's really strange. Could you maybe get me a copy of your db? I need to be able to reproduce this.

**Comment by fernandog** [comment]
@p0psicles database seems ok. I can send you cache.db

first items of both SS

![image](https://cloud.githubusercontent.com/assets/2620870/16494104/76d3ce5c-3ebe-11e6-973f-554606989f98.png)

![image](https://cloud.githubusercontent.com/assets/2620870/16494174/aade3bd8-3ebe-11e6-829c-9e1177d70ae4.png)

**Comment by fernandog** [comment]
@p0psicles sorry, that first one is REPACK, that's why its on top
