### ISSUE TITLE
Can't see season numbers in apibuilder episode.setstatus

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#720]
Can't see season numbers in apibuilder episode.setstatus
develop branch

@medariox 

![image](https://cloud.githubusercontent.com/assets/2620870/16426253/9ccf0b34-3d3e-11e6-950d-6732798685d9.png)

**Comment by labrys** [comment]
@fernandog I assume you're using Firefox?

This appears to be a Firefox specific js issue with `typeahead`, as it works correctly on Chrome, Edge, and IE.

@OmgImAlexis @p0psicles any suggestions?

**Comment by OmgImAlexis** [comment]
What version of typeahead are we on? I remember there being quite a few issues before with it.
Also what version of Firefox is this happening on the Twitter typeahead library only works from version 3.5+

**Comment by labrys** [comment]
I tested this on 46.0 and 47.0.  AFAIK we're on [v0.11.1](https://twitter.github.io/typeahead.js/) which hasn't had any active dev in over a year.

**Comment by labrys** [comment]
Just checked and it looks like we're using `"bootstrap3-typeahead": "~3.1.1",`

**Comment by labrys** [comment]
As discussed in IRC, this appears to be an issue with the `<option label='text'></option>` format and not typeahead.

**Comment by fernandog** [comment]
Firefox 47

**Comment by OmgImAlexis** [comment]
Looks like this may be a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=option-label) that's already got work arounds.

**Comment by fernandog** [comment]
@OmgImAlexis close this as its upstream?

**Comment by OmgImAlexis** [comment]
Yup. That page is being rewritten eventually anyways as it's for apiv1 and we'll need a new cleaner one for apiv2.
