### ISSUE TITLE
[APP SUBMITTED]: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by whipcracker** [pymedusa/SickRage#737]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]**
Operating System: **Linux-3.16.7-ckt25-feral-x86_64-with-debian-8.4**
Locale: UTF-8
Branch: **master**
Commit: PyMedusa/SickRage@d0c1d270f08bc1b84183d81a1ea5b1d70cacc426
Link to Log: https://gist.github.com/a2be5d35ec16bf0b9db436e1d1da5eba
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: [d0c1d27] Data returned from provider is not json
Traceback (most recent call last):
  File "/media/sdq1/home/***********/.medusa/sickbeard/providers/torrentday.py", line 132, in search
    jdata = response.json()
  File "/media/sdq1/home/***********/.medusa/lib/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
@whipcracker This is fixed in develop.  #641

**Comment by fernandog** [comment]
@WhipCracker what is your question? you are never online at IRC - when I'm online - so I can reply

**Comment by whipcracker** [comment]
Hey mate, I ended up submitting the questions as issues on Github instead, as I appear to live in the arse end of the world and no one's on when I'm on (I'm in Australia) but it appears I've found two bugs, which Rato says will be looked at and fixed in Dev soon enough :) 

Otherwise, all good mate, please close this off and I'll see yas (eventually) on IRC :)
