### ISSUE TITLE
[APP SUBMITTED]: -1

### ISSUE THREAD

**Issue by whipcracker** [pymedusa/SickRage#753]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: PyMedusa/SickRage@d0c1d270f08bc1b84183d81a1ea5b1d70cacc426
Link to Log: https://gist.github.com/4b48f8a015bf2e0093ad48fcbf6d71c4
### ERROR
```
TORNADO :: [d0c1d27] API :: error -1
Traceback (most recent call last):
  File "C:\Medusa\sickbeard\server\api\core.py", line 130, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "C:\Medusa\sickbeard\server\api\core.py", line 199, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "C:\Medusa\sickbeard\server\api\core.py", line 2732, in run
    episode_status_counts_total[status] += 1
KeyError: -1
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Is this still an issue? Did it happen again?

**Comment by whipcracker** [comment]
Not that I can remember, honestly. If it pops up again, I'll submit it.
