### ISSUE TITLE
Trakt syncing is removing all episodes from trakt, when episode in lib has no location (not downloaded)

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/SickRage#762]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: fix-lib-trakt/e7a8ac651917f300953e6bd64565b4cd03fb2a6a
OS: Windows
What you did: Enabled trakt syncing with option shown below (screenie)
What happened: When trakt starts syncing, it's adding all episodes that it finds in local medusa lib, to the trakt collections. But after this, it's removing them again, as there is no 'location' configured in the db for that episode.
What you expected: To not remove them after adding.
Logs: NA. No errors or exceptions.
```
PASTE LOGS HERE
```
The option:
![image](https://cloud.githubusercontent.com/assets/1331394/16830410/ffcbe9ca-499e-11e6-9c1e-4a34a921bc32.png)

**Comment by p0psicles** [comment]
This should be fixed for this PR: #501

**Comment by fernandog** [comment]
@p0psicles this is how it should work:

![trakt_medusa](https://cloud.githubusercontent.com/assets/2620870/16850807/1cd888d8-49d7-11e6-8559-6c4746b35d51.png)

**Comment by p0psicles** [comment]
Fixed with https://github.com/pymedusa/SickRage/pull/501/commits/ddd3ef0e1dc9460d2a43bc55babef508d1e037fe#r71357622

**Comment by labrys** [comment]
@fernandog That's not how it should work.  The watch list is a list of shows already watched, not a list of shows that need to be watched.  As Medusa is a PVR and not a media player, IMO we shouldn't be touching a user's watch list.  We handle collections and should only be working with the collections part of trakt.
