### ISSUE TITLE
In latest dev, removing a show (from disk) doesn't work anymore

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/SickRage#765]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop/32f27a76711d07567663f32ed9155881e3454f8b
OS: Windows 7
What you did: Removed a show, and checked to remove from disk
What happened: 

1. Gave an Oops mako error:
```
10:48:58 DEBUG::TORNADO :: [32f27a7] Failed doing web ui request u'delete_show': Traceback (most recent call last):
  File "D:\Development\ManualSearch\sickbeard\server\web\core\base.py", line 250, in get
    method = getattr(self, route)
AttributeError: 'Home' object has no attribute 'delete_show'
```
This was easily fixable in: sickbeard\server\web\home\handler.py, chaning some of the redirects from delete_show to deleteShow.

But then it was giving an exception on removal from disk.
This is because of the self.location properties in tv.py

What you expected:
Logs:
```
10:54:48 INFO::SHOWQUEUE-REMOVE-SHOW :: [d2d1bf3] Attempt to delete show folder D:\Series\Shows\Marvel's Daredevil
Exception in thread SHOWQUEUE-REMOVE-SHOW:
Traceback (most recent call last):
  File "D:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "D:\Development\MedusaSr\sickbeard\show_queue.py", line 755, in run
    self.show.delete_show(full=self.full)
  File "D:\Development\MedusaSr\sickbeard\tv.py", line 1211, in delete_show
    logger.log(u'Show folder does not exist, no need to %s %s' % (action, self.location), logger.WARNING)
  File "D:\Development\MedusaSr\sickbeard\tv.py", line 248, in location
    raise ShowDirectoryNotFoundException("Show folder doesn't exist, you shouldn't be using it")
ShowDirectoryNotFoundException: Show folder doesn't exist, you shouldn't be using it

```

**Comment by p0psicles** [comment]
@pymedusa/developers no more merges before this is in dev pls.

**Comment by ratoaq2** [comment]
Thanks. I'll fix it tonight

**Comment by ratoaq2** [comment]
Just looking the logs and looking the code, I would say that
- the show folder was successfully deleted (can you confirm that?)
- when trying to log the `success`, the exception happens because the location doesn't exist anymore.
- when trying to log the error from the previous step, it fails again because the location doesn't exist anymore.

If you don't want to wait, in addiction to your fix, these changes should fix the issue:

Changing tv.py:1208 to
```
logger.log(u'%s show folder %s' % (('Deleted', 'Trashed')[sickbeard.TRASH_REMOVE_SHOW], self.raw_location))
```
and tv.py:1211 to: 

```
logger.log(u'Show folder does not exist, no need to %s %s' % (action, self.raw_location), logger.WARNING)
```

**Comment by p0psicles** [comment]
Jip that worked. Want me to PR that?

**Comment by ratoaq2** [comment]
Sure... It would be faster
