### ISSUE TITLE
Preview Rename Issue

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/SickRage#768]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

files before rename: http://www.fshare.it/image.jpeg?i=721468588hb
files then manually checked in shows folder and they are renamed when using preview rename. but:
db after rename: http://www.fshare.it/image.jpeg?i=se1468588m4

(had to rename another show so the images above shows the wrong show, but same result both on the page and in db.. old name persists, but file is renamed in folder)

Branch/Commit: develop width dbdebug=1 in config.ini
OS: Windows 8
What you did: tried to rename files
What happened: files were renamed but not updated in database
What you expected: that database would update with new names
Logs: https://0bin.net/paste/QGobOqbhwpjeVoiY#BOYrJHm-wUL3Ldym4+gFz9MUyBBT+jWHvzP2Er4FgXQ

**Comment by ratoaq2** [comment]
Thanks for reporting it.
I've already spotted the bug and it will be fixed later today.

**Comment by wimpyrbx** [comment]
excellent! thanks!

**Comment by wimpyrbx** [comment]
@ratoaq2 tested fix, but i did not achieve any different result. files still get renamed in folder, but not updated in db.

note: if i change episodes to Skipped after rename is done it changes the db. not sure if that info is helpful or not.

**Comment by ratoaq2** [comment]
Do you have the log file for this other test?

**Comment by wimpyrbx** [comment]
no but i'll provide one shortly. tested without debug on

**Comment by wimpyrbx** [comment]
https://0bin.net/paste/MBnwCQND9tVESUEv#Fy7ksWlReVyDgw8+sNX4BRhyfDk-H9UO0BTixBAwyuy

tried to rename two episodes.
EP9 and EP10

**Comment by wimpyrbx** [comment]
sorry! thought it was merged to develop.. testing with new tv.py now!

**Comment by wimpyrbx** [comment]
@ratoaq2 working when updated to new tv.py from PR! Thanks!

**Comment by ratoaq2** [comment]
Great :+1:
