### ISSUE TITLE
warning about mako after restore

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#770]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: develop
Commit: 637381f9ddf2bdfe0899a67bbd8e96ae86ed4f77
OS: 	Linux-3.2.40-i686-with-glibc2.0
What you did: I backup from optimized branch to restore using develop
What happened: I had this warning:
2016-07-15 23:04:52 MAIN :: [9de6b50] Restore: Unable to remove the cache/mako directory: error 2 : No such file or directory
What you expected:
Logs:
https://gist.github.com/NicoLeOca/21e153ab037726e90ef9356899c98ec5

**Comment by NicoLeOca** [comment]
@fernandog 
as discussed issue raised

**Comment by fernandog** [comment]
Looks like a permission issue as medusa check if exists before deleting:
https://github.com/pymedusa/SickRage/blob/develop/SickBeard.py#L144
