### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'undefined'

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#795]
Found this in my log. Don't know what happened:

```

AA ValueError: invalid literal for int() with base 10: 'undefined'
AA    if show and not search_thread.show.indexerid == int(show):
AA  File "/home/osmc/SickRage/sickbeard/manual_search.py", line 164, in collectEpisodesFromSearchThread
AA    episodes_in_search = collectEpisodesFromSearchThread(show)
AA  File "/home/osmc/SickRage/sickbeard/server/web/home/handler.py", line 1000, in manualSearchCheckCache
AA    result = function(**kwargs)
AA  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
AA    result = self.fn(*self.args, **self.kwargs)
AA  File "/home/osmc/SickRage/lib/concurrent/futures/thread.py", line 55, in run
AA    return self.__get_result()
AA  File "/home/osmc/SickRage/lib/concurrent/futures/_base.py", line 398, in result
AA    value = future.result()
AA  File "/home/osmc/SickRage/lib/tornado/gen.py", line 1008, in run
AA    results = yield self.async_call(method)
AA  File "/home/osmc/SickRage/sickbeard/server/web/core/base.py", line 252, in get
```

@pymedusa/developers

**Comment by fernandog** [comment]
no one has any clue about this?

how show = 'undefined' ?

@p0psicles @ratoaq2 @medariox

**Comment by labrys** [comment]
I couldnt find anything that would assign undefined, can you repeat this and possibly identify a show that this might represent?

**Comment by fernandog** [comment]
cant reproduce. will close for now

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@1737c36a92ae2275f8a6eb4ba308b51db3686624
**Link to Log**: https://gist.github.com/74a2ab772c1fcb32c3aeec9257ebdf39
### ERROR
<pre>
2016-12-30 10:49:38 ERROR    Thread-34 :: [1737c36] Exception generated: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\server\web\core\base.py", line 268, in async_call
    result = function(**kwargs)
  File "C:\pymedusaSickRage\medusa\server\web\home\add_shows.py", line 645, in addExistingShows
    indexer_id_given.append((int(indexer), show_dir, int(indexer_id), show_name))
ValueError: invalid literal for int() with base 10: 'None'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
