### ISSUE TITLE
[APP SUBMITTED]: substring not found

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#805]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@05d5356005c899d8a6ec0ef905d9092f578063a3
Link to Log: https://gist.github.com/e90e8494f3d32574b4743fc35ae5365d
### ERROR
```
SEARCHQUEUE-MANUAL-76703 :: [HDSpace] :: [05d5356] Could not find main torrent table
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrent/html/hdspace.py", line 106, in search
    index = response.text.index('<div id="information"')
ValueError: substring not found
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@05d5356005c899d8a6ec0ef905d9092f578063a3
Link to Log: https://gist.github.com/455e184dfb324db3e698372d1267fc8f
### ERROR
```
SEARCHQUEUE-MANUAL-304262 :: [HDSpace] :: [05d5356] Could not find main torrent table
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/providers/torrent/html/hdspace.py", line 106, in search
    index = response.text.index('<div id="information"')
ValueError: substring not found
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
https://github.com/pymedusa/SickRage/blob/05d5356005c899d8a6ec0ef905d9092f578063a3/sickbeard/providers/torrent/html/hdspace.py#L108
Shouldn't be ERROR. Needs to be changed to WARNING or DEBUG.

**Comment by duramato** [comment]
And where does the traceback come from?

**Comment by labrys** [comment]
@ratoaq2 I think this traceback is due to your changes to the logger that modified the log-level for subliminal logging.  Do you think you could look into this?

**Comment by labrys** [comment]
Fixed in split-parsing
