### ISSUE TITLE
fanart background not visible on some pages

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/SickRage#818]
not sure if this is already known, but here goes:

the fanart background added to develop branch only displays on DisplayShow page.
it would be nice to see this background on the following pages as well:
* manual search
* edit page for the show
* preview rename page for the show

**Comment by fernandog** [comment]
@wimpyrbx in progress to manual search

**Comment by Thraxis** [comment]
There were no requests for fanart on other pages other then the initial PR for fanart on the displayShow.  p0psicles requested fanart for the manual search page (which now has a PR) and now that there is a request I will PR the other two pages.

**Comment by fernandog** [comment]
i think we are good with only adding to manual search. Dont know what others think

**Comment by wimpyrbx** [comment]
i myself would vote to have a shows background on all show-related pages.
http://www.fshare.it/image.jpeg?i=dp14694878k

**Comment by duramato** [comment]
I second @wimpyrbx , they are pages of the show

**Comment by Thraxis** [comment]
#820

**Comment by Thraxis** [comment]
These are in the dev branch now
