### ISSUE TITLE
"snatched" line deleted in history after download

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#831]
@pymedusa/developers 
Branch: develop
Commit: e07898539913c511074c68e8557db77f3d814325
Version: fatal: No names found, cannot describe anything.
 Python Version:	2.7.11 (default, Dec 17 2015, 14:08:17) [GCC 4.6.3]
 SSL Version:	OpenSSL 1.0.2e 3 Dec 2015
 OS:	Linux-3.2.40-i686-with-glibc2.0
 Locale:	en_US.UTF-8

What you did: snatched a video (auto or manually doesn't matter)
What happened: after being snatched a line appear in history
when the episode is downloaded, a "downloaded" line appears and the "snatched" disappears
What you expected: the "snatched" to be kept
![capture](https://cloud.githubusercontent.com/assets/9487685/17252514/460964ac-55ad-11e6-8da6-27d0f18f14c3.JPG)
Logs:
https://gist.github.com/NicoLeOca/8500ec6c059f37c0472a01a4944ed035

**Comment by fernandog** [comment]
issue presented in master. Probably after rewrite of history.

**Comment by NicoLeOca** [comment]
Quick again Fernandog
Thanks !

Le 29 juil. 2016 ? 20:18, Fernando <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Closed #831<https://github.com/pymedusa/SickRage/issues/831>.

-
