### ISSUE TITLE
PP does not respect "File Exists"

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#838]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: split-parsing
OS: Ubuntu 14.04
What you did: Nothing, auto PP
What happened: PP keeps post processing an already PPed file (5 times already)
What you expected: To not PP an already PPed file.
Logs: https://gist.github.com/duramato/6b3247b72b393dcc1d34bce926ea4db7

Important log i saw:
`
2016-07-30 14:24:01 WARNING  POSTPROCESSOR :: [378d2ca] Failed to create hardlink of /media/extssd/download/shows/Pokemon.S01.DUB.SDTV.DVD.x264.NG/Pokémon - 1x83 - Pallet Party Panic - SD DVD.mkv at /media/extssd/Shows/Pokémon/Season 01/Pokémon.S01E83..DVDRip-SickRage.mkv. Error: u'error 17 : File exists'. Copying instead
`

**Comment by medariox** [comment]
Probably related to https://github.com/pymedusa/SickRage/commit/61d44d961e1a230226aaf352663e52ca03ba92bd#diff-658028a3149fae625c0afbf06c863dd0L592

**Comment by fernandog** [comment]
@medariox ofc not! he is using split-parsing

**Comment by medariox** [comment]
Exactly, and that change is also in split-parsing. I even linked the diff.

**Comment by fernandog** [comment]
please check the code before blame me.
Can you explain then why  a change in PARSE breaks the symlink?

**Comment by medariox** [comment]
Can someone replicate this?

**Comment by fernandog** [comment]
still waiting logs:

1) Delete hardlink
1) Send logs of the first PP after deletion
2) Send logs of the second PP
3) Send logs in the first fail

@ratoaq2

**Comment by fernandog** [comment]
@ratoaq2 his DB didnt had that episode in tv_episodes table, so when you create TVE object location = None.

maybe we should check somewhere if the episode exists in DB, if not, break the PP of that episode

**Comment by fernandog** [comment]
still an issue? if not, please close
