### ISSUE TITLE
[APP SUBMITTED]: Path does not exist

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/SickRage#892]
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 14:08:17) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@13ce2b7eaaa2343bbe52c53d6c80dc39bcdfd4a5
Link to Log: https://gist.github.com/b6e02c0ec4033d19bac513bd10048aa2
### ERROR
```
FINDSUBTITLES :: [13ce2b7] Exception generated in thread FINDSUBTITLES: Path does not exist
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 745, in run
    self.subtitles_download_in_pp()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/subtitles.py", line 701, in subtitles_download_in_pp
    processTV.has_matching_unknown_subtitles(video_path)):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 699, in has_matching_unknown_subtitles
    Language('und') in get_embedded_subtitles(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/processTV.py", line 710, in get_embedded_subtitles
    subliminal_video = scan_video(video_path)
  File "/usr/local/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 370, in scan_video
    raise ValueError('Path does not exist')
ValueError: Path does not exist
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment]
Do you have any "pre_script" configured?

**Comment by NicoLeOca** [comment]
@rotoaq2
I don't
![error subs](https://cloud.githubusercontent.com/assets/9487685/17650539/b3ed146e-6250-11e6-942d-fff41f179823.JPG)

**Comment by ratoaq2** [comment]
It seems that the video has moved when it started downloading subtitles and before finishing the post process logic. Is that happening all the time or it was a 1 time error?

**Comment by NicoLeOca** [comment]
More a one time

Le 14 ao?t 2016 ? 18:59, Rato <notifications@github.com<mailto:notifications@github.com>> a ?crit :


It seems that the video has moved when it started downloading subtitles and before finishing the post process logic. Is that happening all the time or it was a 1 time error?

-

**Comment by ratoaq2** [comment]
@Nicola, the log in gist wasn't enough since subliminal logs went over 50 lines. Could you provide logs for one case starting when the post process kicks in until the exception occurs? 

And another question? Are your files stored in a remote location relative to medusa?

**Comment by fernandog** [comment]
@NicoLeOca @ratoaq2 do you have autoPP enabled? If so, auto PP probably runned when find subtitle was downloading subs and didn't finished the process. So autoPP found the sub and moved.

with postpone, you should disable auto PP

**Comment by NicoLeOca** [comment]
@ratoaq2 
I don't have more than 3 hours of log history; it's impossible for me to provide more of them.
my files are stored on the same device as Medusa

@fernandog 
autoPP is enabled as well as postpone PP if no subs
I want to keep it that way because I got other sources of media I want to be PP on a regular basis

It's been a couple of months I got it that way and it's the first time I get an error

I suggest to close this issue, and if it happens again on a regular basis, I come back to you

**Comment by fernandog** [comment]
@NicoLeOca maybe its another issue then

please increase log size and number of log files in medusa settings

**Comment by NicoLeOca** [comment]
@fernandog 
done,
change from 5 files of 1MB to 20 of 3 mB
I never noticed I could do that, thanks

I doesn't solve the very issue though

**Comment by fernandog** [comment]
@NicoLeOca can you switch to branch `fix_892` and test?

**Comment by fernandog** [comment]
Don't worry. You can switch back to develop without any issues

**Comment by NicoLeOca** [comment]
but I don't have have files to test on at the moment
I may have to test for a couple of days

I know I can safely come back to develop.
the biggest issue is that I need to uninstall/reinstall to switch branch...

**Comment by fernandog** [comment]
so wait and let's wait we merge the PR then

**Comment by fernandog** [comment]
@NicoLeOca after 7 days, did you had this issue?

**Comment by NicoLeOca** [comment]
@fernandog 
No I haven't so far
thank you
