### ISSUE TITLE
[APP SUBMITTED]: UNIQUE constraint failed: scene_exceptions_refresh.list

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#901]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@c1d222110af35faf2b4ce2e92d1cfbdfdbe6038b
Link to Log: https://gist.github.com/26a441899cca468cbf3b689b27f568fe
### ERROR
```
MAIN :: [c1d2221] Fatal error executing query: UNIQUE constraint failed: scene_exceptions_refresh.list
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/db.py", line 256, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/home/home/SickRage/sickbeard/db.py", line 110, in _execute
    sql_results = self.connection.cursor().execute(query, args)
IntegrityError: UNIQUE constraint failed: scene_exceptions_refresh.list
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato no idea. is this DB being used in SickRage too?

**Comment by duramato** [comment]
No it is not beeing used elsewhere.

**Comment by medariox** [comment]
Will probably be fixed in https://github.com/pymedusa/SickRage/pull/848. There is currently a bug that allows duplicate entries (not a new bug).

**Comment by fernandog** [comment]
But this error its not related to data content

One table has two same row ids (sql issue)

@thraxis confirm?

**Comment by medariox** [comment]
This is exactly what will be fixed in the PR...

**Comment by fernandog** [comment]
still an issue? if no, close please

imho this is a DB issue in db file. not python.
