### ISSUE TITLE
[APP SUBMITTED]: addShowByID() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#902]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@c1d222110af35faf2b4ce2e92d1cfbdfdbe6038b
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [c1d2221] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
TypeError: addShowByID() takes at least 2 arguments (1 given)
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/server/web/core/base.py", line 268, in async_call
    result = function(**kwargs)
TypeError: addShowByID() takes at least 2 arguments (1 given)
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato which show did you try to add?

**Comment by p0psicles** [comment]
Wanted to Comment..  Can you reproduce?

**Comment by duramato** [comment]
Right click open link in New tab on Add show on the imdb list.
