### ISSUE TITLE
KODI library clean runs even if KODI is disabled in settings

### ISSUE THREAD

**Issue by medariox** [pymedusa/SickRage#911]
![kodi](https://snapr.pw/i/8250ae59e2.png)

`
2016-08-18 12:10:08 POSTPROCESSOR :: [e9b8897] No KODI host passed, aborting update
2016-08-18 12:10:08 POSTPROCESSOR :: [e9b8897] KODI library clean failed for host:
`

**Comment by fernandog** [comment]
But only with file replace right?

**Comment by medariox** [comment]
It was happening for a file that was already PP and couldn't be replaced.
How do we differentiate replace from non-replace? I just tried to download one episode that was previously Archived and the log still shows.

**Comment by fernandog** [comment]
We set to clean when we delete any existing file

```python
         # delete the existing file (and company)
         for cur_ep in [ep_obj] + ep_obj.related_episodes:
             try:
                 self._delete(cur_ep.location, associated_files=True)
                 sickbeard.KODI_LIBRARY_CLEAN_PENDING = True
```

https://github.com/pymedusa/SickRage/pull/894#discussion_r75294687

**Comment by fernandog** [comment]
@medariox as the clean wasn't made because there was no host, the flag wasnt set to False, so next PP medusa tried to clean again.
