### ISSUE TITLE
[APP SUBMITTED]: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by fernandog** [pymedusa/SickRage#916]
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.4.16-1-osmc-armv7l-with-debian-8.5**
Locale: UTF-8
Branch: **optimized**
Commit: PyMedusa/SickRage@f3ebd83c2c263ea7406e35dffabebf52d1dbab58
Link to Log: https://gist.github.com/04bf7dddfbca8ff19a53fe94020ba3cf
### ERROR
```
SEARCHQUEUE-MANUAL-247808 :: [T411] :: [f3ebd83] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/osmc/SickRage/sickbeard/providers/torrent/json/t411.py", line 134, in parse\n    title = row[\'name\']\nTypeError: \'int\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/providers/torrent/json/t411.py", line 134, in parse
    title = row['name']
TypeError: 'int' object has no attribute '__getitem__'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@medariox any clue?

**Comment by medariox** [comment]
The provider returned an int instead of the expected dict. Surely a provider issue we don't catch.

**Comment by fernandog** [comment]
@medariox 

```python
logger.log("row: {0}".format(str(row)), logger.WARNING)
```
[T411] :: [f3ebd83] row: 5556688

**Comment by fernandog** [comment]
maybe we can check if row is a `dict` before continue.

**Comment by fernandog** [comment]
@duramato t411 is working for you?
