### ISSUE TITLE
cant add any shows

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/SickRage#927]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)
Medusa Info:	Branch: develop
Commit: dc3ab673b04785a9a5d2d50a9553347a85ff23d8
Version: v0.1.3
Python Version:	2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
SSL Version:	OpenSSL 1.0.2d 9 Jul 2015
OS:	Windows-10-10.0.10586
Locale:	en_US.cp1252
What you did: just tried to add a show
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
2016-08-19 15:01:04 INFO     Thread-27 :: [dc3ab67] TemplateLookupException: Cant locate template for uri u'/inc_add-show-options.mako'


as well as File C:\pymedusaSickRage\lib\mako\runtime.py:795, in _lookup_template:
raise exceptions.TemplateLookupException(str(compat.exception_as()))
TemplateLookupException: Cant locate template for uri u'/inc_add-show-options.mako'
```

**Comment by fernandog** [comment]
@OmgImAlexis

**Comment by fernandog** [comment]
@ripper1967 can you run git commands?

if so before shutdown medusa, disable auto updater
then inside SickRage folder run:
`git reset --hard HEAD~7`

you should see:
```
16:12:50 osmc@osmc:~/SickRage (develop)$ git reset --hard HEAD~7
HEAD is now at d9aa711 Fixed issue blacklist referenced before assignment. (#909)
```

start again

**Comment by ripper1967** [comment]
ok will try in a couple minutes

**Comment by OmgImAlexis** [comment]
@fernandog that was my bad. I renamed all the js and accidently renamed a mako file.
