### ISSUE TITLE
[APP SUBMITTED]: disk I/O error

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#970]
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **fix_add_shows**
Commit: PyMedusa/SickRage@ff495ccaeba8a9ec8c54fb23a4d960cdcdbe8398
Link to Log: https://gist.github.com/c0dcaf85502a0679a7112f52f7278c53
### ERROR
```
EVENT-QUEUE :: [f197b9e] DB error: disk I/O error
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/db.py", line 257, in action
    self.connection.commit()
OperationalError: disk I/O error
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato your HDD is dying 
@medariox

**Comment by medariox** [comment]
Disk is full?

**Comment by duramato** [comment]
No

**Comment by medariox** [comment]
Then probably very busy/extremely slow/about to die HDD.

**Comment by fernandog** [comment]
still an issue? if no, close please
